### ISSUE TITLE
is not matching server-rendered content

### ISSUE THREAD

**Issue by imdunkind** [apexcharts/vue-apexcharts#103]
Greetings, I use nuxt@2.6.3 and faced with the problem. Everything works fine until you refresh the page with the component via F5. After

> [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

```javascript
<template>
   <div>
     <apexchart width="500" type="bar" :options="chartOptions" :series="series"></apexchart>
   </div>
</template>

<script>
export default {
    data: function() {
      return {
        chartOptions: {
          chart: {
            id: 'vuechart-example'
          },
          xaxis: {
            categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
          }
        },
        series: [{
          name: 'series-1',
          data: [30, 40, 35, 50, 49, 60, 70, 91]
        }]
      }
    },
};
</script>
```

plugins/apexcharts.js
```javascript
import Vue from 'vue'
import VueApexCharts from 'vue-apexcharts'

Vue.use(VueApexCharts)
Vue.component('apexchart', VueApexCharts)
```
in nuxt.config.js
```javascript
{ src: '~/plugins/apexcharts.js', ssr: false }
```
package-json
```javascript
"apexcharts": "3.6.11",
"vue-apexcharts": "1.3.5",
```
any idea?

**Comment by imdunkind** [comment]
the problem is solved. I added no-ssr tag

```javascript
<template>
   <div>
     <no-ssr>
       <apexchart width="500" type="bar" :options="chartOptions" :series="series"></apexchart>
     </no-ssr>
   </div>
</template>

<script>
export default {
    data: function() {
      return {
        chartOptions: {
          chart: {
            id: 'vuechart-example'
          },
          xaxis: {
            categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
          }
        },
        series: [{
          name: 'series-1',
          data: [30, 40, 35, 50, 49, 60, 70, 91]
        }]
      }
    },
};
</script>
```

**Comment by giovannimanzoni** [comment]
> the problem is solved. I added no-ssr tag
> 
> ```js
> <template>
>    <div>
>      <no-ssr>
>        <apexchart width="500" type="bar" :options="chartOptions" :series="series"></apexchart>
>      </no-ssr>
>    </div>
> </template>
> 
> <script>
> export default {
>     data: function() {
>       return {
>         chartOptions: {
>           chart: {
>             id: 'vuechart-example'
>           },
>           xaxis: {
>             categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
>           }
>         },
>         series: [{
>           name: 'series-1',
>           data: [30, 40, 35, 50, 49, 60, 70, 91]
>         }]
>       }
>     },
> };
> </script>
> ```

Thanks. And now use <client-only> in Nuxt
