### ISSUE TITLE
Set global options and override defaults

### ISSUE THREAD

**Issue by Diferno** [apexcharts/vue-apexcharts#105]
Hi!
I'm trying to override the default options of the charts (to set the fontfamily for all the legends, axis, etc...) but can't find the correct way to do so.

I have my plugin registered as:
```
  Vue.use(VueApexCharts)
  Vue.component('apexchart', VueApexCharts)
```
And have tryed to override like:
```
VueApexCharts.chartOptions = Object.assign(VueApexCharts.chartOptions, {
    xaxis: {
      labels: {
        style: {
          fontFamily: 'Montserrat'
        }
      }
    }
  })
```
And even trying to set the defaults as I do with axios through 
``` VueApexCharts.props.options ```

Any tips? 
Thx in advance!

**Comment by junedchhipa** [comment]
Can you try setting the global `Apex` variable?

```javascript
Apex.xaxis = {
   labels: {
     style: {
          fontFamily: 'Montserrat'
      }
   }
}
```

This would override the default settings for the x-axis.
Let me know if it worked.

**Comment by joshhoegen** [comment]
@Diferno, any luck with @junedchhipa's suggestion? 

@junedchhipa, are you suggesting that `Apex` === `VueApexCharts` if using Diferno's syntax?

**Comment by junedchhipa** [comment]
`Apex !== VueApexCharts`

`window.Apex` is a global variable and it should be set after importing and registering `Vue-ApexCharts` using 

```javascript
Vue.use(VueApexCharts)
window.Apex.xaxis = { ... }
```

After this, when you use `<apexcharts>` component, it will get the default values first from `window.Apex` and then use your chart's config.

**Comment by joshhoegen** [comment]
Oooohhhh! Thank you very much for this insight, @junedchhipa! This will be beneficial for app light/dark theming!

**Comment by sajaddp** [comment]
@junedchhipa,
Can you help me to change all `font-family` attributes globally?

**Comment by junedchhipa** [comment]
@sajaddp 
To set `font-family` for all elements of the chart, you can use

```javascript
options = {
   chart: {
      fontFamily: 'Courier New', Courier, monospace
   }
}
```

**Comment by manja1227** [comment]
> `Apex !== VueApexCharts`
> 
> `window.Apex` is a global variable and it should be set after importing and registering `Vue-ApexCharts` using
> 
> ```js
> Vue.use(VueApexCharts)
> window.Apex.xaxis = { ... }
> ```
> 
> After this, when you use `<apexcharts>` component, it will get the default values first from `window.Apex` and then use your chart's config.

How can we do it for ng-apexcharts?

window.Apex has no data.
