### ISSUE TITLE
Chart not rendering correctly in foreign languages

### ISSUE THREAD

**Issue by chandler73** [apexcharts/vue-apexcharts#111]
The project I'm working on uses apexcharts to graph data using a simple line graph. When a different localization is selected, the line is not being rendered on the chart. The tooltip can 'see' the data points, which have been plotted but there is no line.

The chart options are coming through correctly. 

Localization for apex charts is working really well.

The chart renders the data into a plotted line correctly when the app is using english. 

My current chart property looks like this: 

chart: {
      type: 'line',
      height: 500,
      zoom: {
        enabled: false
      },
      locales: localeConfigurationObject,
      defaultLocale: 'en'
    }

Any help that could be provided in solving this issue would be greatly appreciated.

**Comment by junedchhipa** [comment]
Please provide a [codesandbox](https://codesandbox.io/s/pwwz8009n0) demo to reproduce easily.

**Comment by chandler73** [comment]
This appears to be an implementation issue, after playing around in codepen. Thank you. Apexcharts is fantastic!
