### ISSUE TITLE
Development flow

### ISSUE THREAD

**Issue by darkoromanov** [apexcharts/vue-apexcharts#113]
I'd like to be more active in helping you with the ApexCharts library but I have some problem for the setup.

I use Vue ApexCharts in a project created with webpack. Now, how can I test my changes to apexcharts library (js not Vue) in a fast way?

I did a checkout of apexharts.js inside my node_modules folder, then I launch 

`npm run dev`

command, so all changes to code are compiled on the fly. The problem is Vue doesn't detect the changes. I also tried:

`npm run dev:cjs`

and 

`npm run dev:esm`

but with no luck.

**Comment by junedchhipa** [comment]
The recommended way of working on the apexcharts library is to consider `apexcharts.js` and `vue-apexcharts` independent.
I work on [apexcharts.js](https://github.com/apexcharts/apexcharts.js#development) separately by cloning it another folder and then doing `npm run dev`.
The roll-up will detect the changes in src of core-apexcharts library whenever you save files inside `src` folder.

Most of the time, changes are only required in the core-library, but if you need to do some changes in the wrapper libraries as well, you should import the apexcharts by the relative path and not from node_modules.

Here is an example

```
├── apexcharts/
| ├── dist/
| │   └── apexcharts.min.js
| ├── src/
| │   └── apexcharts.js
├── vue-apexcharts/
| ├── src/
| │   └── vue-apexcharts.js
```

In the vue-apexcharts.js, target the core `apexcharts.js` by 
```
import apexcharts from '../../dist/apexcharts.min.js'
```

Hope this helps!

**Comment by darkoromanov** [comment]
you mean I should replace 

`import ApexCharts from 'apexcharts'`

in index.js

with

`import apexcharts from '../../dist/apexcharts.min.js'`

Thanks!

**Comment by junedchhipa** [comment]
Yes, depending on the folder structure you have, you can do that.
Before pushing the code / before creating PR, you should remove the relative path import and revert it to the original `import ApexCharts from 'apexcharts'`
