### ISSUE TITLE
Toolbar: customize hamburger menu

### ISSUE THREAD

**Issue by sgergo** [apexcharts/vue-apexcharts#114]
Hello!

I really like this chart but unfortunately I cannot find a way to customize the hamburger menu. I'd like to:
1. remove the 'Download SVG' option
2. change the menu background to dark 

My apologies if I missed something in the Docs :) Thank you!

**Comment by LazeBear** [comment]
I'm looking for a way to change the hamburger icon as well.
I found this ticket from the [apexcharts.js repo](https://github.com/apexcharts/apexcharts.js/issues/481)
but adding that `toolbar` property doesn't work.

**Comment by sgergo** [comment]
This is actually an example how to override the defaults, however I could not change the background color. 

https://codepen.io/apexcharts/pen/pxZKqL

**Comment by bitmover-studio** [comment]
> This is actually an example how to override the defaults, however I could not change the background color.
> 
> https://codepen.io/apexcharts/pen/pxZKqL

I had the same problem and I was able to solve it with CSS

.apexcharts-menu{
	background-color: #27293d!important;
	border: 0px;
}

I hope that helps you

**Comment by danielkpodo** [comment]
Thanks this really helped

**Comment by Abhijeet452** [comment]
Thank You so much

**Comment by UsmanAzhigov** [comment]
They have a component with the ps options parameter that accepts a theme object with the mode key (values: dark or light). You can customize other colors in this object if the standard component theme doesn't suit you.
