### ISSUE TITLE
Series not redrawn when clicking on legend

### ISSUE THREAD

**Issue by markusand** [apexcharts/vue-apexcharts#115]
First series that is hidden by clicking on the legend is not redrawn again. All other series are redrawn as expected.

Reproduced the error in this fiddle https://jsfiddle.net/markusand/0mp7x2at/

**Comment by markusand** [comment]
I've noticed an effect when using 2 sibling charts with the same series data that may have some relation ¿? with this issue:

On clicking a serie in legend of any of the two charts, this serie disappears from both charts. However, when clicking all subsequent series only disappear in their own chart.

**Comment by bf** [comment]
I also have this issue when using vue-apexcharts in Nuxt.js. 
But I think this might be an issue with apexcharts itself, what makes you think this is caused by vue-apexcharts?

**Comment by markusand** [comment]
> what makes you think this is caused by vue-apexcharts?
I have no idea. It may be an error from apexcharts library, my experience is with Vue.

**Comment by bf** [comment]
If I go to https://apexcharts.com/vue-chart-demos/area-charts/spline/ and try clicking the legend, this bug happens. Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by cahuayamarcial** [comment]
Hopefully there is a solution soon.

**Comment by junedchhipa** [comment]
Released v1.5.0 which fixes the issue.
The problem was occurring because the `deep` watch was causing 2 renders.

**Comment by cahuayamarcial** [comment]
great <3!
