### ISSUE TITLE
parentHeightOffset has no effect

### ISSUE THREAD

**Issue by elijahworkz** [apexcharts/vue-apexcharts#122]
When drawing a chart (vue) there's always too much room on the bottom of the chart which is very noticeable when displaying chart in a bordered box.
I was trying to set parentHeightOffset to 0 but it seems to have no effect.

see this example - https://codesandbox.io/s/vue-basic-example-xzjd8?fontsize=14

When playing with pure apexCharts - I can see the difference when setting parentHeightOffset to 0 - https://codesandbox.io/s/competent-knuth-7q35y?fontsize=14

**Comment by junedchhipa** [comment]
You just need to upgrade `apexcharts@3.8.2` and `vue-apexcharts@1.4.0` to latest versions.
Update demo - https://codesandbox.io/s/parentheightoffset-1uql5
