### ISSUE TITLE
Toggling series generate some errors

### ISSUE THREAD

**Issue by AndreaMinato** [apexcharts/vue-apexcharts#124]
Hi, first of all thank you for this amazing project.

I experienced some errors using the official vue wapper and I believe that they are all related to the action of toggling the series:

### Problem 1 (as reported on #115 )
When I toggle the first serie it does disappear but after that it doesn't redraw when I toggle it again

[apexcharts](https://apexcharts.com/vue-chart-demos/line-charts/data-labels/) **working**
[vue-apexchart](https://apexcharts.com/vue-chart-demos/line-charts/data-labels/) **not working**

### Problem 2 (related to [#337](https://github.com/apexcharts/apexcharts.js/issues/367))
When I toggle a serie in the tootltip it stops showing the values grouped and instead each line is treated separately in tooltip

[apexcharts](https://apexcharts.com/javascript-chart-demos/area-charts/stacked/) **working**
[vue-apexchart](https://apexcharts.com/vue-chart-demos/area-charts/stacked/) **not working**

### Problem 3
If one of my series has constant values when I toggle all the other ones the tooltip stops working properly

[apexcharts](https://codepen.io/andreaminato/pen/WqPwrp?editors=1010) **working**
[vue-apexchart](https://codepen.io/andreaminato/pen/dBabBM) **not working**

If in the first chart of the non working example I toggle the First serie it will report the following tooltip
![image](https://user-images.githubusercontent.com/15440218/60964699-442d3e80-a314-11e9-949d-e973f66e444a.png)

**Comment by junedchhipa** [comment]
You're right!
Looks like a major bug, wondering why no one experienced it yet in `vue-apexcharts`.
Thanks for reporting, I will take a detailed look soon.

**Comment by junedchhipa** [comment]
Released vue-apexcharts v1.5.0 which fixes the issue.
The problem was occurring because the `deep` watch was causing 2 renders.
