### ISSUE TITLE
Minified distribution

### ISSUE THREAD

**Issue by hc-codersatlas** [apexcharts/vue-apexcharts#126]
Hi, can you please provide a minified distribution in dist? Thanks.

**Comment by junedchhipa** [comment]
Minify the `apexcharts` build?
This commit - https://github.com/apexcharts/apexcharts.js/commit/58f25f7afa9a0c32302de9bde3c7c1dd70f31512 fixes it.

From the next versions, core `apexcharts` library will serve minified files by default.

**Comment by hc-codersatlas** [comment]
Thanks, does this apply to vue-apexcharts as well?
