### ISSUE TITLE
Chart goes out of the parent div

### ISSUE THREAD

**Issue by mreorhan** [apexcharts/vue-apexcharts#133]
When the page loaded first time, charts going out the div.
![chart](https://user-images.githubusercontent.com/17215194/62051329-cde97100-b21b-11e9-99e9-470467017b39.PNG)
And I cant change the height of charts. (like auto)

**Comment by junedchhipa** [comment]
Can you please create a minimal codesandbox demo of the issue?

**Comment by mreorhan** [comment]
> Can you please create a minimal codesandbox demo of the issue?

Im using with vuetify. So thats ready component. I didnt change anything. I couldnt create with codesandbox.

**Comment by maweigl** [comment]
Same problem here. I assume you also want to put your apexchart into a v-card such as in this short example:
```
<v-card>
    <v-card-title class="overline">
      {{ title }}
    </v-card-title>
    <v-card-text v-if="loaded">
    <apexchart :type="type" :options="options" :series="series"></apexchart>
    </v-card-text>
  </v-card>
```
Any suggestion about how to force the apexchart to always stay withing the v-card-text boundaries and completely fill its width/height?

**Comment by 00GeekInside00** [comment]
For the time being, here is a hacky workaround that worked for me:

Template:
```
 <v-col lg="3" md="6" cols="12" class="pt-0">
<!-- Using v-card classes in template -->
<!-- Class "pie" created to simulate the card behavior -->
          <div
            class="v-card v-card--link v-sheet v-sheet--tile theme--light pie"
            style="height:200px;max-height:200px;"
          >
             <apexchart type="pie" :options="chartOptions" :series="series"></apexchart>
          </div>
```


Style:
```
.pie:hover {
  box-shadow: 3px 3px 3px 3px rgb(177, 175, 175);
  transition: all 0.4s ease-out;
}
```

**Comment by dollinvans** [comment]
OK I know It's been a while. Has anybody found a solution yet?
