### ISSUE TITLE
Zoom autoScaleYaxis not works.

### ISSUE THREAD

**Issue by bunnyxt** [apexcharts/vue-apexcharts#134]
I use vue ApexCharts to draw an area chart and I hope it can zoom in x direction and hope y axis can adjust itself(max value and min value). I found autoScaleYaxis property and set it to true, however, it doesn't works. I even download example in this repo and set autoScaleYaxis: true and then run it, it doesn't work as well. 

Part of chartOptions  are as below.

```
chartOptions: {
  chart: {
    zoom: {
      enabled: true,
      type: "x",
      autoScaleYaxis: true // seems it doesn't work...
    }
  }
}
```

![Screen Recording 2019-08-01 at 10 38 31 2019-08-01 10_39_42](https://user-images.githubusercontent.com/32478279/62314807-c35fef00-b448-11e9-98dd-6cf106343b61.gif)

Yaxis doesn't adjust into smaller scale when I zoom in.

So is it a bug? Hope you can help me asap. Thanks.

**Comment by junedchhipa** [comment]
This commit https://github.com/apexcharts/apexcharts.js/commit/64b1d3c6888dce850d4d5e26861a6cce2643406b fixes the issue.
The patch will be released soon.
