### ISSUE TITLE
Question: How to use toggleDataPointSelection with Donut / Pie

### ISSUE THREAD

**Issue by luansievers** [apexcharts/vue-apexcharts#136]
Hello.
Im trying to use `toggleDataPointSelection` with a donut chart but it dont seem to work, keeps telling me `Element Not found`
I tried with `this.$refs.donutChart.toggleDataPointSelection(0, 0)`

**Comment by junedchhipa** [comment]
Similar to #129

**Comment by junedchhipa** [comment]
If the chart is not mounted before you call this method `this.$refs.donutChart.toggleDataPointSelection(0, 0)`, it will result into `Element not found` error.

You should try 

```javascript
options: {
  chart: {
    events: {
       mounted: function(chartContext, config) {
          chartContext. toggleDataPointSelection(0)
       }
    }
  }
}
```

**Comment by VincentVanclef** [comment]
> If the chart is not mounted before you call this method `this.$refs.donutChart.toggleDataPointSelection(0, 0)`, it will result into `Element not found` error.
> 
> You should try
> 
> ```js
> options: {
>   chart: {
>     events: {
>        mounted: function(chartContext, config) {
>           chartContext.toggleDataPointSelection(0)
>        }
>     }
>   }
> }
> ```

Is there some issues with events in this library? mounted doesnt trigger, and if you navigate away from the chart and back, the events dont work anymore (click for example).

code: https://pastebin.com/rC2hpQnY

I have to use the component hooks @xxx those work.
