### ISSUE TITLE
Toggling legend for the first series doesn't work in Vue

### ISSUE THREAD

**Issue by cahuayamarcial** [apexcharts/vue-apexcharts#139]
Se presentó un error cuando trato de ocultar una opción en la misma página:

https://apexcharts.com/vue-chart-demos/area-charts/spline/

Cuando doy clic en Series 1, oculta correctamente pero deja de mostrar.

**Comment by bf** [comment]
This issue seems to be the same as https://github.com/apexcharts/vue-apexcharts/issues/115#issuecomment-523659392 

When you click the legend to toggle the data series, it does not work for the first element. It removes the series but then the toggle button in the legend is broken.

**Comment by bf** [comment]
If I go to https://apexcharts.com/vue-chart-demos/area-charts/spline/ and try clicking the legend, this bug happens. Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by cahuayamarcial** [comment]
Hopefully there is a solution soon.

**Comment by junedchhipa** [comment]
Yeah, I noticed the bug.
Closing this in favour of #145 
A fix will be released soon, thank you for the patience.
