### ISSUE TITLE
"u.parser.draw is undefined"

### ISSUE THREAD

**Issue by siulca** [apexcharts/vue-apexcharts#14]
Using Vue Cli 3, the basic GitHub example generates the following error:

`Unhandled promise rejection TypeError: "u.parser.draw is undefined"`

And no chart displays. Am I missing something?

Update: The chart example works in the root of my project but not inside a component that is being used as a router-view. Unsure if that's relevant but just in case.

**Comment by junedchhipa** [comment]
Updated the examples folder with `vue-router` usage. I don't get this error.
If it is possible for you to create a live demo (maybe using codesandbox) of the issue you are facing, I can look more.

**Comment by siulca** [comment]
OK, I isolated the problem. It only occurs when the chart is inside Buefy tabs! : /

**Comment by siulca** [comment]
I isolated and reproduced the problem here: https://codesandbox.io/s/w0p7152kn5

(Please ignore the lack of styling, you can still click the tabs names, so Buefy is working as expected)

As you can see the chart outside the tabs works. The chart inside the first tab, doesn't. Open the developer tools to see the following error.

![screen shot 2018-10-08 at 19 06 24](https://user-images.githubusercontent.com/6707451/46625834-554ee200-cb2d-11e8-80a2-1d82a9293349.png)

**Comment by junedchhipa** [comment]
The codesandbox demo works on my side 
![screen shot 2018-10-09 at 12 27 37 pm](https://user-images.githubusercontent.com/17950663/46651806-cb4f5980-cbbe-11e8-9997-725c16550f2d.png)

Just to confirm - what version of ApexCharts and Vue-ApexCharts did you use in that demo?

**Comment by siulca** [comment]
AH! It's a browser specific issue. 

It doesn't work in **Firefox** (Mac) but works on Chrome and Safari (Mac). I'll check in windows later. 

These are the dependencies versions I'm using:
![screen shot 2018-10-09 at 08 33 46](https://user-images.githubusercontent.com/6707451/46653496-215fd500-cb9e-11e8-8ebd-6e88e7439bfc.png)

**Comment by siulca** [comment]
The demo works in Chrome and Edge on Windows 10. **It doesn't work in Firefox.** 

Is this fixable?

**Comment by junedchhipa** [comment]
I tested in Firefox, and yes it doesn't work there. Strangely, on resize, it starts working.

The error is generating from SVG.js and I don't know what checks they are doing at that stage.
I don't have an immediate fix, but I will get back at the end of this week if this is fixable or not.

**Comment by siulca** [comment]
Thank you for following this up. Meanwhile I'm building my own charts as the other options out there look too corporate and I'm building a site/app for a game. I think there's dire need for a library of charts that doesn't look like it didn't came out of excel. Something that looks 'cute' and non-threatening to less data literate audiences. If you know of any existing libraries for Vue, please let me know. I have looked at dozens and they are all very similar, or lacking features. Thank you again.

**Comment by junedchhipa** [comment]
I don't have a specific name but you can find a list of Vue specific charting libraries here
https://madewithvuejs.com/charts

I think it's just a matter of playing with colors, borders, fonts, etc to customize charts instead of building a new one. If you have any design in mind, share here - so I can assist/let you know if it is possible with ApexCharts (if the above bug is fixed, of course!)

**Comment by junedchhipa** [comment]
I had to move svg.js dependency to ApexCharts /src as there are other issues arising in the core svg.js code. Until they release v3.0.0, I will have to keep track of the changes manually.

I have fixed the buefy issue and will release a patch very soon.

**Comment by junedchhipa** [comment]
v2.1.4 released
