### ISSUE TITLE
Selection problem

### ISSUE THREAD

**Issue by xiaojun515688** [apexcharts/vue-apexcharts#141]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/29938116/63633611-d9468580-c67d-11e9-9ce7-46319e5106f6.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/29938116/63633658-743f5f80-c67e-11e9-9d80-36a744cec3d6.png">

**Comment by BenjaminListwon** [comment]
Actually, looks like fixed in 1.5.0

https://github.com/apexcharts/vue-apexcharts/commit/377352610656138a75efd3057859780929820ae7
