### ISSUE TITLE
How to change a label value dynamically of the radial chart?

### ISSUE THREAD

**Issue by songjy0718** [apexcharts/vue-apexcharts#142]
Hi~ 

I am using like this:

![image](https://user-images.githubusercontent.com/20220995/63671856-84d90c80-c81b-11e9-8be2-79e964db247a.png)

![image](https://user-images.githubusercontent.com/20220995/63671989-e4371c80-c81b-11e9-8b37-c34a427d316c.png)
![image](https://user-images.githubusercontent.com/20220995/63672009-eef1b180-c81b-11e9-8dd1-5150d90d9dd4.png)

![image](https://user-images.githubusercontent.com/20220995/63672022-f6b15600-c81b-11e9-9712-a9f742b654ad.png)

My sample datas is like this: 

[{"url":"/sample1","resource":{"percents":[{"name":"a","use":10},{"name":"e","use":70},{"name":"f","use":20},{"name":"g","use":60}]}},
{"url":"/sample2","resource":{"percents":[{"name":"d","use":14},{"name":"b","use":10},{"name":"c","use":30},{"name":"f","use":50}]}}]

I can change the series dynamically, but I don't know how to change the labels.
How to change a label value dynamically of the radial chart?

Thanks!

**Comment by thriggs** [comment]
I'm also interested in hearing the solution to this question.

**Comment by mcmiro** [comment]
You have to call updateOptions method for the ref attribute. Like in my example: I did 

`<VueApexCharts
          v-if="showChart"
          type="radialBar"
          ref="realtimeChart"
          :options="chartOptions"
          :series="series"
        ></VueApexCharts>`

`this.$refs.realtimeChart.updateOptions({
  labels: ["A", "B", "C", "D"],
});`
