### ISSUE TITLE
Chart changes size when label is too big

### ISSUE THREAD

**Issue by Ymayro** [apexcharts/vue-apexcharts#143]
Good day.

I am trying to create a pie chart but if my labels are too big the chart changes it's size almost to the point you can't see it on the page. It contains around 20 different labels which with a little more than 100 chars on it.

**Comment by landwire** [comment]
I have the same Problem. Reduced the font-size and tried to use plotoptions: size but that gave me unexpected results.

**Comment by junedchhipa** [comment]
Can I see an example, please?
[Codesandbox](https://codesandbox.io/s/pwwz8009n0) demo?
