### ISSUE TITLE
Series Re-Rendering Issue using legend

### ISSUE THREAD

**Issue by jsinhSolanki** [apexcharts/vue-apexcharts#145]
Hello,
If we toggle series using legend, only first series got this issue. If I click on the first series it gets disappeared from chart but when I click it again it doesn't get re-rendered.

It also happens in demo charts. Please check below GIF for re-production.
![apex-series](https://user-images.githubusercontent.com/31243533/64180354-44fccf80-ce82-11e9-8184-17ace3e2f676.gif)

**Comment by junedchhipa** [comment]
Released vue-apexcharts v1.5.0 which fixes the issue.
The problem was occurring because the `deep` watch was causing 2 renders.

**Comment by ZedObaia** [comment]
Great news !!
It would be better to update the demo as well, it's still using the old version.
