### ISSUE TITLE
Vue Charts | Missed data for hided datasets

### ISSUE THREAD

**Issue by Alex-Sokolov** [apexcharts/vue-apexcharts#149]
**Codepen**
vue-apexcharts codesandbox: https://codesandbox.io/s/vue-basic-example-vced7

apexcharts: 3.8.5
vue-apexcharts: 1.5.0

Legend options:
```
legend: {
          show: true,
          showForSingleSeries: true,
          showForNullSeries: true,
          showForZeroSeries: true,
          formatter: (seriesName, opts) => {
            let legendTitle = seriesName;

            const globals = opts.w.globals.series[opts.seriesIndex];
            const config = opts.w.config.series[opts.seriesIndex].data;

            legendTitle = legendTitle + " — " + globals + " — " + config;

            return legendTitle;
          }
        },
```

**Explanation**
It is necessary to display the total amount near the data set in the legend. To do this, we use the custom formatter method to generate it. But when hiding the set, access to dataset is lost both from config and globals. Looks like mutating original array

<img width="546" alt="Снимок экрана 2019-09-05 в 14 14 41" src="https://user-images.githubusercontent.com/4497128/64337193-8955b000-cfe7-11e9-99af-c6690fedbf81.png">
<img width="547" alt="Снимок экрана 2019-09-05 в 14 14 37" src="https://user-images.githubusercontent.com/4497128/64337192-88bd1980-cfe7-11e9-8e41-4181ad9e8a00.png">

**Comment by BenjaminListwon** [comment]
Actually, looks like fixed in 1.5.0

https://github.com/apexcharts/vue-apexcharts/commit/377352610656138a75efd3057859780929820ae7

**Comment by junedchhipa** [comment]
Yes, the original series is mutated to delete the series and calculate the chart values again. Not the best solution, but it was implemented initially, I may change it in the future.

For now, you can do it like this:
 - Move `series` to computed props and 
 - Duplicate series in formatter by this.series.slice()

```javascript
<template>
  <div class="app">
    <apexcharts width="550" type="bar" :options="chartOptions" :series="series"></apexcharts>
  </div>
</template>

<script>
import VueApexCharts from "vue-apexcharts";

export default {
  name: "Chart",
  components: {
    apexcharts: VueApexCharts
  },
  computed: {
    series: function() {
      return [
        {
          name: "series-1",
          data: [30, 40, 45, 50, 49, 60, 70, 81]
        },
        {
          name: "series-2",
          data: [10, 20, 45, 54, 13, 80, 30, 60]
        }
      ];
    }
  },
  data: function() {
    return {
      chartOptions: {
        chart: {
          id: "vuechart-example"
        },
        legend: {
          formatter: (seriesName, opts) => {
            let legendTitle = seriesName;

            const ser = this.series.slice();
            const s = ser[opts.seriesIndex].data;

            legendTitle = legendTitle + " — " + s;

            return legendTitle;
          }
        },
      }
    };
  }
};
</script>
```

Codesandbox - https://codesandbox.io/s/access-to-series-lost-in-formatter-u3nq2

**Comment by junedchhipa** [comment]
Turns out, the above solution doesn't work when I checked again.
I will prevent original array mutation so it doesn't cause these issues.
