### ISSUE TITLE
[Vue-ApexCharts] Zooming doesn't work with custom numeric xaxis

### ISSUE THREAD

**Issue by vlad909** [apexcharts/vue-apexcharts#15]
Hello! :)
I'm trying to use zoom with custom array of data:
```
 chartOptions: {
                       chart: {
                        id: 'vuechart',
                        toolbar: { show: true },

                        zoom: {
                            enabled: true,
                            type: 'x',
                        }
                    },
                    xaxis: { 
                        categories: [0, 2, 4, 6, 8, 10]
                    }
                }
```

But tools with settings for zoom don't appear. if I remove 'xaxis' option than this code will works fine with standard xaxis list [1,2,3,...]:
```
chartOptions: {
                      chart: {
                        id: 'vuechart',
                        toolbar: { show: true },

                        zoom: {
                            enabled: true,
                            type: 'x',
                        }
                    }
                }
```
How I can use zoom with custom array for xaxis? I know that zooming will not be enabled for category x-axis charts, but only for charts having numeric x-axis. For eg., timeline charts, but...
I apologize if the question is stupid :(
ty very much!

**Comment by junedchhipa** [comment]
You're right.
Zooming should be possible in numeric x-axis which is currently not implemented.

I just modified the code to support zooming on the numeric x-axis and it will be released tomorrow

**Comment by junedchhipa** [comment]
This commit https://github.com/apexcharts/apexcharts.js/commit/9f3032b84a09d63a66576ccc3b7318b8266decfa fixes it.

**Comment by vlad909** [comment]
@junedchhipa tomorrow? very nice! thanks for the help and quick answer! I'm in your debt 👍

**Comment by vlad909** [comment]
@junedchhipa again thanks! works nice :)
