### ISSUE TITLE
Reactivity loss (from 1.4.0 to 1.5.0)

### ISSUE THREAD

**Issue by y-nk** [apexcharts/vue-apexcharts#155]
### Demo
https://codesandbox.io/embed/vue-basic-example-1slm9

### How to reproduce : 

1. click the generate button several times. it works well.
2. change vue-apexcharts version to 1.5.0
3. retry 1., it doesn't work anymore

**Comment by junedchhipa** [comment]
`deep` watch is disabled since v1.5.0.

Now, the correct way to update series is

```
this.series = [{
  data: newSeries
}]
```

and for options
```
this.chartOptions = {...this.chartOptions, ...{
    xaxis: {
        labels: {
           style: {
             colors: ['red']
           }
        }
    }
}}
```

**Comment by y-nk** [comment]
@junedchhipa is there a reason why disable deep watch (so i could explain it to my team as well) ?

**Comment by junedchhipa** [comment]
@y-nk The deep watch causes multiple renders and degrades performance.
