### ISSUE TITLE
Hide series in the legend

### ISSUE THREAD

**Issue by jokerstudios** [apexcharts/vue-apexcharts#157]
Hello first of all, thank you for the amazing library.
It looks amazing and works perfectly.

I have one question regarding the legend.
I want to hide a series from the legend but don't know how to achieve that?
Can you give me a code example or a hint on how to achieve this?

Thanks

**Comment by junedchhipa** [comment]
Which version of `apexcharts` and `vue-apexcharts` are you using?
Because the previous versions had issues with legend hiding series.

**Comment by jokerstudios** [comment]
Entries from the package.json

"apexcharts": "^3.8.5",
"vue-apexcharts": "^1.4.0",
