### ISSUE TITLE
[Enhancement] Add wordWrap Label

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/vue-apexcharts#161]
Would be great to have an easy way to add a breakline on the labels So I could put

"Mon
10/10"

Instead of "Mon 10/10"

I am using "ddd dd/MM" it would be great if it accepted \r\n for the breakline. Or via any other way. Some charts uses boolean variables to break by space or even a width value.

Best regards

**Comment by junedchhipa** [comment]
This is implemented in v3.15.2
https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/
