### ISSUE TITLE
Can`t drag left or right vertical bar chart on touch devices

### ISSUE THREAD

**Issue by igorveremsky** [apexcharts/vue-apexcharts#166]
Hi, on touch device after zoom in on vertical bar chart i can't drag it. Seems like its core bug because it also don't work on your official demos page too:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13087365/67118927-a688bb80-f1ee-11e9-938a-f79d17511fe0.gif)

**Comment by junedchhipa** [comment]
Panning on touch devices is not supported yet.

**Comment by anton-brass** [comment]
is there any plan to support it in the near future?

**Comment by Niid** [comment]
Hi there ! Is there any update regarding an eventual support of touch panning ?
Have a nice day.

**Comment by bchellingworth** [comment]
+1

**Comment by kotran88** [comment]
still not yet...
