### ISSUE TITLE
HSL color get's converted to grey

### ISSUE THREAD

**Issue by TarikTz** [apexcharts/vue-apexcharts#169]
If I try to use HSL color format I get it converted to rgb(153,153,153).

`colors: ['hsl(212, 71%, 49%)']`

Any way to use HSL color scheme in my project?

**Comment by junedchhipa** [comment]
Sorry, but that is not supported yet.
The safest way is to use hex colors which is supported in all places. RGB is supported in certain properties, not all.

**Comment by TarikTz** [comment]
That's a bit of a bummer. I guess I'll have to created it by myself then.

**Comment by junedchhipa** [comment]
Yeah, there are color conversion utilities that will allow you to do it easily.
It would add a good amount of size to the library, hence I didn't add it.

**Comment by isacvale** [comment]
Thanks for the help TarikTz. @junedchhipa you really should seriously support for hsla. This is a presentation tool that lacks support to colors! This decision really hurts your tool.
