### ISSUE TITLE
Updating yaxis min and max

### ISSUE THREAD

**Issue by microwavesafe** [apexcharts/vue-apexcharts#17]
I'm trying to update the yaxis min and max through the options object
```
<apexcharts type="line" :options="options" :series="series"></apexcharts>
```
```
data() {
  return {
    options: {
      yaxis: {
        min: undefined,
        max: undefined,
      },
    },
  }
}
```
```
yRangeChanged(min, max) {
  this.options.yaxis.min = min;
  this.options.yaxis.max = max;
 }
```
But this doesn't work. The object is correctly updated, but the Y axis range stays the same. If I manually set yaxis.min and yaxis.max to begin with, the graph displays correctly. I noticed a commit which added a Yaxis prop, but it looks like this was taken out straight away.

Am I missing something when trying to update these values?

**Comment by microwavesafe** [comment]
If I create a new object it does work
```
yRangeChanged(min, max) {
  this.options = {...this.options, ...{
    yaxis: {
      min: min,
      max: max,
    }
  }}
}
```

**Comment by microwavesafe** [comment]
Looking at the code
```
    this.$watch('options', options => {
      if (!this.chart && options) {
        this.init()
      } else {
        this.chart.updateOptions(this.options, true);
      }
    })
```
would it help to add the deep: true property?
```
    this.$watch('options', options => {
      if (!this.chart && options) {
        this.init()
      } else {
        this.chart.updateOptions(this.options, true);
      }
    }), { deep: true })
```

**Comment by junedchhipa** [comment]
Which version of apexcharts/Vue-apexcharts are you using?

Here is a codesandbox demo of updating yaxis values working correctly.

**Comment by microwavesafe** [comment]
I can confirm that this method works
```
yRangeChanged(min, max) {
  this.options = {
    yaxis: {
      max: max,
      min: min
    }
  }
}
```
but if we add the deep: true property, couldn't I do this?
```
yRangeChanged(min, max) {
  this.options.yaxis.min = min;
  this.options.yaxis.max = max;
 }
```
I guess there's not much in it, it just looks a bit neater.

**Comment by junedchhipa** [comment]
The `deep` property will unnecessarily fire update event for tiny changes.

For eg, in your example

```javascript
yRangeChanged(min, max) {
  this.options.yaxis.min = min;
  this.options.yaxis.max = max;
}
```

the updateOptions method would fire twice

**Comment by microwavesafe** [comment]
Fair point. I do get a strange side affect though when using 
```
yRangeChanged(min, max) {
  this.options = {
    yaxis: {
      max: max,
      min: min
    }
  }
}
```
I have a data set with 60 points, if I initially set my xaxis min to 0 and max to 10, it correctly shows the first 10 points. Then I change the yaxis min and max with the above code. It resets my axis range to 0 to 60, even if I do this.
```
yRangeChanged(min, max) {
  this.options = {
    yaxis: {
      min: min,
      max: max,
    },
    xaxis: {
      min: 0,
      max: 10
    }
  }
},
```
is this the expected behaviour?

**Comment by junedchhipa** [comment]
No, not expected behavior.

Working example on [codesandbox](https://codesandbox.io/s/7w051y7v7x)

**Comment by microwavesafe** [comment]
By the way, thanks for all your help. I've tried copying all my settings into the codepen and your quite right, it doesn't behave like that. But when I run exactly the same code on my site, it rescales the X as well. I can't see any difference in how we're doing it.

For now I will manually edit the data series to just what I need, this will have the same effect.
