### ISSUE TITLE
Is there any way to change the color with negative value on linechart?

### ISSUE THREAD

**Issue by nickgayo12** [apexcharts/vue-apexcharts#175]
![image](https://user-images.githubusercontent.com/46472012/68188834-ff28c880-ffe4-11e9-8e97-8b4e80811aa6.png)

Is there any way to change the color with negative value on linechart?

@junedchhipa 

Any help would be so much appreciated, Thank you!

**Comment by IsraelOrtuno** [comment]
I would also like if this is possible in a column chart
