### ISSUE TITLE
Can't add custom class name(s) to elements

### ISSUE THREAD

**Issue by Elaniobro** [apexcharts/vue-apexcharts#176]
I am not seeing anywhere you may add a custom class name to any of the elements. Ideally I would like to be able to add a custom class name to the component so I may have more control.

Namely I would like to add `overflow: visible` to the `svg` element so when the labels "float" I may position them and see them below the yaxis.

**Comment by Elaniobro** [comment]
I have tried passing in a class name and style as well.
```html
<VuexApexCharts
  :class="{ chart }
  width="300"
  height="60"
  type="bar"
  :options="chartOptions"
  :series="series"
  style="overflow:visible"
/>
```

**Comment by Elaniobro** [comment]
*sigh* I had `scoped` in the `<style>` tag.

**Comment by Robby777** [comment]
Thanks Elaniobro, it saved me alot of time :)
