### ISSUE TITLE
ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by jeff-hykin** [apexcharts/vue-apexcharts#178]
## My Install process
```shell
npm install apexcharts --save
npm install --save vue-apexcharts
```

```js
import VueApexCharts from 'vue-apexcharts'
Vue.use(VueApexCharts)
Vue.component('apexchart', VueApexCharts)
```

## My use case
Copied and pasted this demo
https://apexcharts.com/vue-chart-demos/area-charts/irregular-timeseries/

## The result
![Screen Shot 2019-11-11 at 8 49 53 PM](https://user-images.githubusercontent.com/17692058/68637637-d745d300-04c4-11ea-8da8-de16c4fc64c1.png)
![Screen Shot 2019-11-11 at 8 50 13 PM](https://user-images.githubusercontent.com/17692058/68637648-e298fe80-04c4-11ea-9c19-daa858649daf.png)

## My (successful) workaround
`npm install moment --save`

```js
import moment from 'moment'
window.moment = moment
```

**Comment by junedchhipa** [comment]
Yes, moment is an optional dependency if you want to format the DateTime using it.
Glad you resolved it.

**Comment by jeff-hykin** [comment]
I wouldn't consider this closed
- The demo doesn't work without this additional code
- The error doesn't explain what needs to be done to resolve the issue
- Setting a global `moment` variable can conflict with other packages that need different versions, and is considered by most to be extremely bad practice
