### ISSUE TITLE
Add appendData method to component

### ISSUE THREAD

**Issue by microwavesafe** [apexcharts/vue-apexcharts#18]
I wanted to use the appendData method of apexchart, if we add
```
appendData: function appendData(newData) {
  this.chart.appendData(newData);
}
```
to the methods of the component, we can access this through Vue's refs
```
<apexcharts ref="chart" type="line" :options="options" :series="series" />
```
```
this.$refs.chart.appendData(valueArray);
```

**Comment by junedchhipa** [comment]
Sure, this method along with all other methods of core ApexCharts library will be added soon.

**Comment by junedchhipa** [comment]
Added all the methods of core ApexCharts library to the Vue-component.
Please update to v1.2.3

**Comment by nwaughachukwuma** [comment]
@junedchhipa I cannot call .resetSeries on component `this.$refs.chart` or this.$apexcharts.exec

**Comment by msmuskan** [comment]
Hi, is there something similar to call 'appendData' inside a React component?

The below doesn't work out:-
<img width="466" alt="Screenshot 2020-12-14 at 11 52 29 PM" src="https://user-images.githubusercontent.com/32387220/102145401-6e6b2000-3e67-11eb-81fe-227b6e702ac0.png">
