### ISSUE TITLE
X-axis issue: passing strings changes formatting of chart

### ISSUE THREAD

**Issue by cwlittle** [apexcharts/vue-apexcharts#180]
When I pass a number into the x-axis, I get results like this
<img width="1341" alt="Screen Shot 2019-11-16 at 10 24 36 PM" src="https://user-images.githubusercontent.com/15937987/69003058-cc25e500-08c0-11ea-8ab1-c47b719a63df.png">

However, when I try to convert this to a HH:MI:Sec.milisecond string and pass that, it yields the following
![Screen Shot 2019-11-16 at 9 46 58 PM](https://user-images.githubusercontent.com/15937987/69003057-c92af480-08c0-11ea-87a1-c8498c45b9be.png)

I don't quite understand what is happening under the hood when the type of the x-axis array changes, but it seems as if the formatting is completely changed. How can this be corrected?

**Comment by junedchhipa** [comment]
The `xaxis.type` accepts `numeric, category or datetime`. 

If you have numeric values on the x-axis, it's better to use `numeric` type.
If you have datetime values, use the `datetime` type
Type `category` can be used for any kind of value and can be formatted with custom formatters.
