### ISSUE TITLE
Bug of pie and donut

### ISSUE THREAD

**Issue by jmy520** [apexcharts/vue-apexcharts#182]
![image](https://user-images.githubusercontent.com/14031844/69299899-b6137e00-0c4c-11ea-96b8-54899e8beb2b.png)
![image](https://user-images.githubusercontent.com/14031844/69299930-ca577b00-0c4c-11ea-89c9-19d39a254d82.png)
![image](https://user-images.githubusercontent.com/14031844/69300458-39819f00-0c4e-11ea-9d43-2775860b6ddc.png)

Look at the pictures.I just write one diagram.But render two diagram on the page.It's very strange.Has any body know what's happen. Tell me and thanks a lot.

**Comment by junedchhipa** [comment]
This is fixed in the latest version of apexcharts - v3.11.2
https://cdn.jsdelivr.net/npm/apexcharts@latest
