### ISSUE TITLE
Apexchart height not working as intended

### ISSUE THREAD

**Issue by nishanksisodiya** [apexcharts/vue-apexcharts#188]
Vue-Apexchart height is set to 250px and same chart is repeated in v-col 3 times, but the sizes of these charts are not same at all first one is small second in medium and third is full size idk whats wrong code is too complex to properly reproduce.
here is the row where chart sits 
`<v-row
            no-gutters
          >
            <v-col
              v-for="n in 3"
              :key="n"
              sm="4"
            >
              <apexchart type=radialBar :options="top.chartOptions" :series="top.series" height="250"/>
            </v-col>
          </v-row>`
 and chart options
`top: {
        series: [76, 67, 61, 90],
        chartOptions: {
          sparkline: {
            enabled: true
          },
          height: 250,
          plotOptions: {
            radialBar: {
              startAngle: 0,
              endAngle: 270,
              hollow: {
                size: '30%',
                background: 'transparent'
              },
              dataLabels: {
                name: {
                  show: false
                },
                value: {
                  show: false
                }
              }
            }
          },
          colors: ['#0097a7', '#f44336', '#c6ff00', '#9c27b0'],
          labels: ['Vimeo', 'Messenger', 'Facebook', 'LinkedIn'],
          legend: {
            show: true,
            floating: true,
            fontSize: '12px',
            position: 'left',
            labels: {
              useSeriesColors: true
            },
            itemMargin: {
              horizontal: 1
            }
          },
          responsive: [{
            breakpoint: 480,
            options: {
              legend: {
                show: false
              }
            }
          }]
        }
      },`
![chart](https://user-images.githubusercontent.com/24984652/71509666-1a5fd800-28b2-11ea-809f-5776cd1f0409.gif)
as seen in gif the sizes snap back to normal as soon as the page is resized, this all code is contained in a dialog box of width 600px

**Comment by nishanksisodiya** [comment]
i'm stupid i was using v-layout in vuetify 2 and expecting it to work changed it to v-container and it is working as expected now

**Comment by junedchhipa** [comment]
No worries. It happens to all of us :)
