### ISSUE TITLE
Toolbar show only hamburger for download

### ISSUE THREAD

**Issue by ariefsn** [apexcharts/vue-apexcharts#190]
Hi, I just implement the Apexchart to my Vue app.
I want to show the toolbar, but only the hamburger that appeared.
Here's my options, with default config for toolbar.
![image](https://user-images.githubusercontent.com/33569737/71537948-eb02a700-2955-11ea-8ed5-681cab7793e3.png)

**Comment by junedchhipa** [comment]
If your chart's xaxis is not datetime, then zooming tools are not available.
Category xaxis doesn't support zooming yet.

**Comment by ariefsn** [comment]
Oh I see,
Does that also apply to customIcons?
Because when I activate the customIcons the toolbar becomes blank.

**Comment by ariefsn** [comment]
I've got this warning in the console
![image](https://user-images.githubusercontent.com/33569737/71573178-1d0e3780-2b15-11ea-97ee-1464cc235587.png)

**Comment by junedchhipa** [comment]
Can you please paste your code here that you tried?
Or please create a codepen.

**Comment by junedchhipa** [comment]
Closing as no response and cannot reproduce.
