### ISSUE TITLE
Change language locale dinamically

### ISSUE THREAD

**Issue by jmformenti** [apexcharts/vue-apexcharts#191]
Hi,

The documentation about [language locale](https://apexcharts.com/docs/options/chart/locales/) explains that:

> defaultLocale: String
> 
> You can specify a default locale if you have set multiple locales. Later on, you can also override the locale dynamically by calling chart.setLocale('fr') also.

How can I call _chart.setLocale_ in the vue component?

**Comment by junedchhipa** [comment]
I missed adding the setLocale() method to the Vue instance.
I will soon add it and update the docs too.

Meanwhile, you can add a ref to the `<apexchart>` component and call it like this

```javascript
<template>
  <div class="example">
    <apexchart ref="demoChart" width="500" :options="chartOptions" :series="series"></apexchart>
  </div>
</template>

<script>
  functionName: function() {
    this.$refs.demoChart.setLocale('en')
  },
</script>
```

**Comment by jmformenti** [comment]
When I try the temporary solution I get this error: `TypeError: this.$refs.demoChart.setLocale is not a function`

Perhaps I misunderstood the response, here a simple code with that error:
```vue
<template>
  <div class="example">
    <apexchart ref="demoChart" width="500" :options="chartOptions" :series="series"></apexchart>
  </div>
</template>

<script>
import apexchart from "vue-apexcharts";

export default {
  components: {
    apexchart
  },
  data() { 
    return {
      series: [{
          name: "Desktops",
          data: [10, 41, 35, 51, 49, 62, 69, 91, 148]
      }],
      chartOptions: {
        chart: {
          height: 350,
          type: 'line',
        },
      },
    }
  },
  mounted () {
    this.$refs.demoChart.setLocale('en')    
  },
}
</script>
```

**Comment by junedchhipa** [comment]
Oops, I am sorry.
It has to be
```javascript
this.$refs.demoChart.chart.setLocale('en')
```

**Comment by jmformenti** [comment]
Thanks a lot!
