### ISSUE TITLE
Update options in synced charts

### ISSUE THREAD

**Issue by luscl1** [apexcharts/vue-apexcharts#192]
I have two synchronized charts. Now I want to change the options of one without changing it on the other one. (change height of the chart) In the documentation I found that updateOptions has the parameter updateSyncedCharts. (Link to the docs: https://apexcharts.com/docs/methods/)

As it didn't work and still changed the height of both charts I looked at your code and found that the method updateOptions doesn't have a parameter updateSyncedCharts.

The function updateOptions from your code:
updateOptions (newOptions, redrawPaths, animate) {
      return this.chart.updateOptions(newOptions, redrawPaths, animate)
},

Is this only available for JavaScript and not yet for Vue.js? Are you already on it? 

Many thanks in advance

**Comment by junedchhipa** [comment]
Thanks for reporting.
The param should be there in Vue too.
I will add it soon.

**Comment by luscl1** [comment]
Do you add this new commit to a new npm package? Or is there another way that I can update it in my project?

**Comment by junedchhipa** [comment]
I will release a new version tonight or tomorrow.
