### ISSUE TITLE
Demo page memory usage

### ISSUE THREAD

**Issue by Christilut** [apexcharts/vue-apexcharts#193]
I think the demo page is maybe a bit too memory heavy...
![image](https://user-images.githubusercontent.com/3471363/72161550-9aad2f80-33c0-11ea-830c-a503e03c4593.png)

Before this Chrome told me to close other tabs because I didn't have enough memory. I have 32GB in this machine and only ~50% was in use.

![image](https://user-images.githubusercontent.com/3471363/72161587-b1ec1d00-33c0-11ea-81f6-d80d9809c0a7.png)

**Comment by junedchhipa** [comment]
Which page?
this one? - https://apexcharts.com/javascript-chart-demos

**Comment by junedchhipa** [comment]
Thanks for reporting, that was a bug in the last update.
Fixed it.

**Comment by Sai2024-oss** [comment]
Hi @junedchhipa ,

Can you please help me how to resolve above issue?(Is the above-mentioned "Not enough memory to open this page" & "Aw snap" resolved? Can anyone please help me in resolving this issue?)
