### ISSUE TITLE
Height/width property bug

### ISSUE THREAD

**Issue by alexshv** [apexcharts/vue-apexcharts#194]
Hi. You have bug in init method. 
Whatever height and width I pass, height/width are overriden with this.height/this.width, which are equal to (height: 100%, width: auto). Can you fix this please.

Please take a look, I left comment in this place:

```
init () {
      const newOptions = {
        chart: {
          type: this.type || this.options.chart.type || 'line',
          height: this.height,
          width: this.width,
          events: {}
        },
        series: this.series
      }

      Object.keys(this.$listeners).forEach((evt) => {
        newOptions.chart.events[evt] = this.$listeners[evt];
      });

      const config = this.extend(this.options, newOptions);

      this.chart = new ApexCharts(this.$el, config)
      return this.chart.render()
    }
```

**Comment by junedchhipa** [comment]
Do you also provide `height`/`width` in `<apexcharts>` component?
If yes, height and width in `<apexcharts>` component should override the options properties which is the correct behavior.

**Comment by alexshv** [comment]
I provide it like this:
```
        chart: {
          type: 'area',
          height: 250,
          width: '100%'
        }
```

**Comment by junedchhipa** [comment]
You should provide it directly in the props
`<apexcharts height="250" width="100%">`

This way, props will take precedence over the options.
