### ISSUE TITLE
Empty space on area charts with few values

### ISSUE THREAD

**Issue by yairspi** [apexcharts/vue-apexcharts#196]
Hi, I have an area chart that sometimes has only 7 values, which results in large empty space on the left and right of the area (see image).

I have the latest version (3.15.0). I have tried playing with the padding as per [this issue](https://github.com/apexcharts/vue-apexcharts/issues/44). However, padding 0 seems already in place, and negative padding would make the background horizontal lines go over the y axis, making it unreadable.

Is there anything I can do about this? Many thanks.

![apex-space](https://user-images.githubusercontent.com/3593095/72539779-c83e2100-3877-11ea-855a-faeb359c97e7.png)

**Comment by junedchhipa** [comment]
Try

```javascript
xaxis: {
  type: 'category',
  tickPlacement: 'on'
}
```

**Comment by yairspi** [comment]
Thank you @junedchhipa for the quick response, unfortunately this makes no difference.

These are my chartOptions:
`chartOptions: {
    chart: {
        id: 'zones-chart'
    },
    xaxis: {
        type: 'category',
        tickPlacement: 'on',
    },
    yaxis: {
        min: 0,
    },
    stroke: {
        curve: 'straight'
    },
    fill: {
        type: 'gradient',
        gradient: {
            shadeIntensity: 1,
            opacityFrom: 0.7,
            opacityTo: 0.9,
            stops: [0, 90, 100]
        }
    },
    dataLabels: {
        style: {
            colors: ['black']
        }
    },
}`

**Comment by junedchhipa** [comment]
What is in `series`?

**Comment by yairspi** [comment]
It is loaded by AJAX, so initially empty name and empty data array, and when loaded e.g.
`{"name":"","data":[{"x":"Jan 10","y":129},{"x":"Jan 11","y":30},{"x":"Jan 12","y":646},{"x":"Jan 13","y":497},{"x":"Jan 14","y":623},{"x":"Jan 15","y":804},{"x":"Jan 16","y":534}]}`

**Comment by junedchhipa** [comment]
I think you are using an old version of ApexCharts.
I tried your code and got this result.

![Screen Shot 2020-01-17 at 12 51 36 AM](https://user-images.githubusercontent.com/17950663/72555914-96eb4280-38c3-11ea-9518-be2c41c8da87.png)

Make sure to upgrade apexcharts to 3.15.2
```
npm i --save apexcharts@3.15.2
```

**Comment by yairspi** [comment]
3.15.2 plus the tickPlacement did it - fantastic!
