### ISSUE TITLE
Bars always use the same color.

### ISSUE THREAD

**Issue by hifall** [apexcharts/vue-apexcharts#20]
I am using the bar chart like this:

```
        <apexcharts
                width="300"
                height="250"
                type="bar"
                :options="options"
                :series="series">
        </apexcharts>
```

```
data: () => {
      return {
        options: {
          chart: {
            id: 'Chart'
          },
          colors: ['#41B883', '#E46651', '#E46651']
        },
        series: [{
          name: 'Count',
          data: [30, 40, 10]
        }]
      }
  }
```

The chart shows; however, all three bars use the same color, which is the first one ('#41B883').

How can I make the bars use all the colors specified?

Thanks!

**Comment by junedchhipa** [comment]
To give a different color to each bar, you have to turn on the `distributed` property to true
options = {
  plotOptions: {
    bar: {
        distributed: true
    }
  }
}

https://apexcharts.com/docs/options/plotoptions/bar/#distributed

**Comment by hifall** [comment]
Ah, okay. Sorry I did not go through the docs thoroughly.

Thanks a lot for your help!

**Comment by alexpopa-work** [comment]
@junedchhipa Saved me a lot of trouble! The answer is two years old but it still saves lives

**Comment by MaximeK7** [comment]
Enabling `distributed` disables series highlight when hovering the legend

**Comment by juanmiguel431** [comment]
I cannot get the horizontal bar chart works with the property `distributed `set to true. I want the horizontal bar charts have different colors. How can I get that?

**Comment by ensinho** [comment]
@junedchhipa Thanks a lot! Worked for me as well!
