### ISSUE TITLE
Chaning theme from dark to light and vise versa, not changing

### ISSUE THREAD

**Issue by MisterJ936** [apexcharts/vue-apexcharts#203]
im trying to change theme but doesnt change.  I created a function to change the options.theme.mod = 'dark'. But doesnt change. please help?

**Comment by junedchhipa** [comment]
Which version of apexcharts are you using? I remember fixing this recently.
Can you please post a codepen to reproduce it?

**Comment by cnokobe** [comment]
Or maybe just the "e" on "mode" is missing?

**Comment by junedchhipa** [comment]
Closing as no response.

**Comment by markchristianlacap** [comment]
check issue #400
