### ISSUE TITLE
y-axis is reversed and the position of tooltip is also reversed.

### ISSUE THREAD

**Issue by r4k0nb4k0n** [apexcharts/vue-apexcharts#207]
![issue-apexchart-vue-yaxis-reversed-tooltip-weird](https://user-images.githubusercontent.com/5409746/75349931-f4be7180-58e8-11ea-84e3-92e2f8f55598.gif)

https://codepen.io/r4k0nb4k0n/pen/JjdWpPE

The code in Vue is not working, but in pure js, it works well... and I don't know where the wrong part is.

Thank you for your contribution.

**Comment by junedchhipa** [comment]
The issue seems to be with core apexcharts and not vue-apexcharts.
Just to confirm, what versions of `apexcharts` & `vue-apexcharts` are you using?

**Comment by r4k0nb4k0n** [comment]
```
"apexcharts": "^3.11.1",
"vue-apexcharts": "^1.5.1"
```

Here it is.

**Comment by r4k0nb4k0n** [comment]
```
# yarn remove vue-apexcharts apexcharts
# yarn add vue-apexcharts apexcharts
```

```
"apexcharts": "^3.16.0",
vue-apexcharts": "^1.5.2"
```

Solved this problem by just updating them.

Thank you for your contribution all the time.
