### ISSUE TITLE
too slow when updating

### ISSUE THREAD

**Issue by Alex-CodeLab** [apexcharts/vue-apexcharts#208]
I'm using vue+apexcharts, my chart has about 1000 datapoints, and updates every 20seconds. 
But is is so slow that eventually it crashes the browser.

What are the options to make it faster? 
are there things that can be disabled?

**Comment by junedchhipa** [comment]
Make sure you have these things disabled to maximize performance

1. Animation `chart.animations.enabled = false`
2. Markers size set to 0 `markers.size = 0`
3. Disable DataLabels `dataLabels.enabled = false`

**Comment by prettyboy42** [comment]
> Make sure you have these things disabled to maximize performance
> 
> 1. Animation `chart.animations.enabled = false`
> 2. Markers size set to 0 `markers.size = 0`
> 3. Disable DataLabels `dataLabels.enabled = false`

Hi, I had the same problem. I've just tried as you said but it seems still slow render chart! In my case, I have a dashboard with multiple charts. When button On/Off legend trigger, it will update chartOptions in a chart component like below:
`
this.chartOptions = Object.assign({}, this.chartOptions, {
      legend: {
        show: showLegend
      }
 });
`
Any advice for this? Thank you.

**Comment by lucacalcaterra** [comment]
Same issue here ...

**Comment by bagaskarala** [comment]
same issue

**Comment by tol64** [comment]
> Make sure you have these things disabled to maximize performance
> 
> Animation chart.animations.enabled = false
> Markers size set to 0 markers.size = 0
> Disable DataLabels dataLabels.enabled = false

Unfortunately, these recommendations did not work. Updating the charts is very slow. And the more charts in the window, the more delay. 

The code for playback:

```
            this.chartOptions = {
                chart: {
                    foreColor: textColor
                }
            };
```

**Comment by carbler** [comment]
Mismo problema aqui

**Comment by Ali-Rooholamini** [comment]
Hi.
i had the same issue and fixed it with defineAsyncComponent : 

`const lazyChart = () => {
    return defineAsyncComponent({
        loader: () => import("vue3-apexcharts"),
        loadingComponent: PLoading,
    });
};`

`<component
                    v-if="loadChartTemplate"
                    :is="lazyChart()"
                    type="bar"
                    height="160"
                    :options="chartOptions"
                    :series="chartSeries"
/>`

give me salavat mohammadi pleasing
