### ISSUE TITLE
vue-apexcharts height option doesent work while height prop works

### ISSUE THREAD

**Issue by Qadosch** [apexcharts/vue-apexcharts#209]
# Bug report

One cannot use height inside options object.

## Codepen

Modify [this codepen](https://codesandbox.io/s/pwwz8009n0) with **height: "200px",**
```
chartOptions: {
        chart: {
        height: "200px",
        id: "vuechart-example"
        },
```

or look at this codepen i forked from someone
https://codepen.io/qadosch/pen/WNvpXYZ
row 98 is height: "200px",

## Explanation

- Expectation: it shoud react to height in options object the same it reacts in an [non vue environement](https://codepen.io/qadosch/pen/RwPpLRJ)

- Instead nothing happend at all, not even errors

**Comment by lampewebdev** [comment]
Also setting this via the `responsive` option does not work.
The height is also ignored.

**Comment by Marahin** [comment]
I can also confirm that it doesn't work on my end when I'm setting ApexCharts `options.chart.height`, while it works if I set `<ApexChart height="230">` (so props work, passing in options - doesn't).

**Comment by jra11** [comment]
Also confirmed on my side, with v3.33.1

**Comment by Sandr0oo** [comment]
Confirmed too

**Comment by Davidriquelme** [comment]
So the only thing to do is to force a Re render every time the height changes ?
