### ISSUE TITLE
Examples can't be built

### ISSUE THREAD

**Issue by lukasleitsch** [apexcharts/vue-apexcharts#21]
The command `npm run serve` for serving the examples throw the following error:

```
ERROR  Failed to compile with 1 errors                                                                                                                   

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
```

I use node v8.12.0 and npm 6.4.1

**Comment by junedchhipa** [comment]
I have added `.eslintrc.json` in the root of examples directory.
Pull the latest commit and let me know if it works now.

**Comment by lukasleitsch** [comment]
Is the master branch up to date? The last commit in the master branch is 9 days ago.

**Comment by lukasleitsch** [comment]
Thanks for your update unfortunately I get the error furthermore. I copied the `.eslintrc.json` in the project root. That helps as a workaround but I don't understand this behavior.

**Comment by junedchhipa** [comment]
Did copying the .eslintrc.json to the root of the repository worked? If yes, then I create a file there too, so other users don't get this error.

Even I don't understand this behavior as the same project runs fine on my local. Maybe it is due to some global settings which I have on my machine related to eslint.

**Comment by junedchhipa** [comment]
btw, did you run `npm install` in example directory? 
My fault, if I haven't specified that in README

**Comment by lukasleitsch** [comment]
Yes, I changed into `example` and run `npm install` in this folder. And the `node_modules` folder was created in the `example` folder.

> Did copying the .eslintrc.json to the root of the repository worked? 
Yes, that works. But actually the `example` folder and the repository root should be independent. Each folder have his own `packeage.json`. 

I havn't any global eslint setting on my machine.

**Comment by junedchhipa** [comment]
> The example folder and the repository root should be independent. Each folder have his own packeage.json.

Yes, you're right. And that's why I put `eslintrc.json` in examples directory only. I will look more into what is causing the issue. If you find anything, please create a PR as some other users also faced the same issue.
