### ISSUE TITLE
The series of data disappears in the bound table when click on the legend

### ISSUE THREAD

**Issue by syue1126** [apexcharts/vue-apexcharts#213]
**Does anyone know why the series of data disappears in the bound table when I click on the legend?
Although I clicked again, it's still the same....lol**

[https://codepen.io/ming-syue/pen/ZEGazXq](https://codepen.io/ming-syue/pen/ZEGazXq)

Thx.

**Comment by junedchhipa** [comment]
ApexCharts modifies the original data (which shouldn't be the case actually)

A workaround is to keep the original data at another place and then point that data in series.
https://codepen.io/apexcharts/pen/bGdQVOy
