### ISSUE TITLE
Problem with nuxtjs and remote api

### ISSUE THREAD

**Issue by sleleko** [apexcharts/vue-apexcharts#214]
Hello! Please help: How correctly add working with remote json api in nuxt with remote json api ? After read documentation here https://apexcharts.com/docs/update-charts-from-json-api-ajax/
I,m trying this :
![Снимок экрана 2020-03-10 в 10 33 30](https://user-images.githubusercontent.com/2923963/76282800-a59a1880-62ba-11ea-835a-d60db16cfa06.png)

_/plugins/vue-apexcharts.js file:_ 
```
import Vue from 'vue'
import VueApexCharts from 'vue-apexcharts'

Vue.use({
    install(Vue, options) {
        Vue.component('apexchart', VueApexCharts)
    }
})
```
_section plugins in nuxt.config.js file:_
```
 plugins: [
    '~/plugins/app.js',
    '~/plugins/axios.js',
    '~/plugins/fontawesome.js',
    '~/plugins/filters.js',
    '~/plugins/modal.js',
    '~/plugins/table.js',
    '~/plugins/vue-apexcharts.js',
  ],
```
_section template in mychart.vue file where I,m trying work with charts:_
```
<template>
    <div>
        <apexchart type=bar height=600 :options="chartOptions" :series="series" ref="newchart" />
    </div>
</template>
```
_Versions_
```
    "apexcharts": "^3.16.0",
    "nuxt": "^2.0.0",
    "vue": "^2.6.11",
    "vue-apexcharts": "^1.5.2"
```

**Comment by sleleko** [comment]
Remote api return me this data:
{
    "total": 12,
    "rows": [
        100,
        110,
        123,
        100,
        70,
        900,
        20,
        100,
        144,
        154,
        170,
        200
    ],
}

**Comment by nickgayo12** [comment]
I will just post here what I have done with mine.

_/plugins/vue-apexcharts.js file:_

`import Vue from "vue";
import VueApexCharts from "vue-apexcharts";
Vue.use({
    install(Vue, options) {
        Vue.component("apexcharts", VueApexCharts);
    }
});`

_section plugins in nuxt.config.js file:_

`plugins: [
        { src: "~/plugins/components/chart/vue-apexcharts", mode: "client" }
 ],`

_section template in mychart.vue file where I,m trying work with charts:_

`<template>
    <div>
        <apexchart type=bar height=600 :options="chartOptions" :series="series" ref="newchart" />
    </div>
</template>`

**Comment by sleleko** [comment]
Thank you!
Solved.
In near future, I,ll write pull request to official documentation with example of solution for nuxt
