### ISSUE TITLE
`opts` being `undefined` when applying brush and selection to `rangeBar` charts

### ISSUE THREAD

**Issue by r4k0nb4k0n** [apexcharts/vue-apexcharts#215]
![issue-apexchart-rangebar-brush-opts-undefined](https://user-images.githubusercontent.com/5409746/76296745-04cb4d80-62fa-11ea-885e-2510f98d93b7.gif)

I'm using `"vue-apexcharts": "^1.5.2"`, `"apexcharts": "^3.16.1"`.

When I add brush and selection into chart options, it keeps logging error of `opts` being `undefined`. Does brush support rangeBar?

[![Edit ApexCharts: Brush feature](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/apexcharts-brush-feature-66dsd?fontsize=14&hidenavigation=1&theme=dark)

**Comment by junedchhipa** [comment]
Yes, brush does support rangeBar chart.
But, there is a bug in the tooltip which is causing `opts` being undefined.
I will fix it soon.
