### ISSUE TITLE
How combine several type of charts with different mode work on one apexchart instance vue ?

### ISSUE THREAD

**Issue by sleleko** [apexcharts/vue-apexcharts#216]
How combine several type of charts with different mode work on one apexchart instance vue ?

We have:
1 series with type bar with any data (blue color)
2 series with type bar, by default its blank (no data) (orange color)
3 series with type bar with any data (green color)
4 series with type line (red color)

If in series 2 we will add any data, so how series 1 and series 2 change to bar with stack mode and combine it with 3 series and 4 series who don't be in stack mode ?

See pic with example
![Снимок экрана 2020-03-11 в 15 48 04](https://user-images.githubusercontent.com/2923963/76409846-cb094e00-63b0-11ea-9980-2018114dfef7.png)

**Comment by mika76** [comment]
This help? https://apexcharts.com/vue-chart-demos/mixed-charts/line-column-area

**Comment by sleleko** [comment]
> This help? https://apexcharts.com/vue-chart-demos/mixed-charts/line-column-area

Hello! Unfortunately this example does not fit, because option **stacked** in this code
```
chart: {
              height: 350,
              type: 'line',
              stacked: false,
            },
```
Can applied only for all chart . I'ts right ?

**Comment by mika76** [comment]
Ah I see - there seems to be a note on the `stacked` option that it can't be used with mixed charts... https://apexcharts.com/docs/options/chart/stacked/

**Comment by sleleko** [comment]
> Ah I see - there seems to be a note on the `stacked` option that it can't be used with mixed charts... https://apexcharts.com/docs/options/chart/stacked/

So then if I use several series with a type such as a bar. Then how do I get some columns to stack and some not?

**Comment by mika76** [comment]
It doesn't seem that you can currently - I tried it in a codepen now and was not successful...

**Comment by sleleko** [comment]
> It doesn't seem that you can currently - I tried it in a codepen now and was not successful...

Thank you! I,m think that I must use click events on columns, for open other more detailed stacked column graph. 

In documentation I,m see this future, but how its works when using vue or nuxt js ?
I'll try to use them
