### ISSUE TITLE
Changing chart type, labels and series at same time

### ISSUE THREAD

**Issue by cnokobe** [apexcharts/vue-apexcharts#218]
Hello,

I'm passing an object to my vue component which contains:
- series for line and bar
- series for pie
- labels for line and bar
- labels for pie 
On button click the correspondent series and labels are set, but there are some strange behaviors:
Clicking "pie" and then "bar" - the chart is not drawn at all.
Clicking "line" and then "pie" - the labels are not updated.
This is demo:
https://codepen.io/cnokobe/pen/WNvyZEB

On my project I have also another problems, which I couldn't reproduce on codepen:
Clicking from line or bar to pie I got this error:
_

> Error: <path> attribute d: Expected number, "…089430898 0 0 1 NaN NaN L 233.16…".

_
And on clicking back from pie to line/bar:
_

> It is a possibility that you may have not included 'data' property in series.

_

I think that all the problems are caused because of changing series and options immediately after that. I guess there is some workaround to clean the chart and then set series and options, but everything I tried so far was unsuccessful.

Any help will be appreciated, thanks.

**Comment by junedchhipa** [comment]
In such case, use the function `ApexCharts.exec` to avoid multiple updates.

```javascript
chartOptions: {
  chart: {
    id: 'chart-id'
  }
}

ApexCharts.exec('chart-id', 'updateOptions', {
  series: [...],
  chart: {
    type: 'area'
  },
  xaxis: {
    categories: [...]
  }
})
```
