### ISSUE TITLE
Date display functionality issue on x-axis.

### ISSUE THREAD

**Issue by hardikzignuts** [apexcharts/vue-apexcharts#219]
Can I display first date in mm/dd format as 2/01 instead of Feb '20 ?
Please refer below image for reference.

![Image111](https://user-images.githubusercontent.com/35481220/77145722-59678900-6aaf-11ea-8837-bacf7de079cd.png)

Please help me to resolve this problem.
Thank in advance!

**Comment by cnokobe** [comment]
I think you should try to check the docs:
https://apexcharts.com/docs/options/xaxis/

You need something like this I guess:
xaxis.labels.formatter = function(val) { 
                if(!val) return "0";
                var dt = new Date(val);
                return dt.getMonth() + "/" + dt.getDate();
            }

**Comment by junedchhipa** [comment]
```javascript
xaxis: {
  type: 'datetime',
  labels: {
    format: 'MM/dd'
  }
}
```

**Comment by hardikzignuts** [comment]
@junedchhipa Thank you for your help. I have implement the solution provide by you and issue resolved.

@cnokobe Thanks for your quick response.
