### ISSUE TITLE
Series names don't work with the latest apexcharts verion

### ISSUE THREAD

**Issue by lukasleitsch** [apexcharts/vue-apexcharts#22]
With the latest version of apexcharts.js the series names don't work. In the version 2.1.5 the series names work.

You can see this issue in your line charts example. The series are named with `series-1` and `series-2`. I guess it is an issue of vue-apexcharts because the examples of the apexcharts repo work without this issue.

**Comment by junedchhipa** [comment]
The series names in line chart example are named as `series-1` and `series-2`.
Can you reproduce the issue on somewhere ([codesandbox](https://codesandbox.io))?

**Comment by junedchhipa** [comment]
Ah!! that should not happen.
Thanks for reporting. Looking asap
