### ISSUE TITLE
Datetime Area Chart won't update

### ISSUE THREAD

**Issue by albydnc** [apexcharts/vue-apexcharts#222]
Hi,
I have added to my project the Datetime axis example.
When in the Vue app I update the series by pushing new data to the array, the chart does not update. In console I have seen that the data is written correctly.

```
vueApp.series[0].data.push([Date.now(),newVal.payload])
vueApp.series[0].data.shift()
```

**Comment by albydnc** [comment]
the workaround I have found is to rewrite the entire series array:
```
var newSeries = [{name:"series",data:vueApp.series[0].data}]
newSeries[0].data.push([Date.now(),newVal.payload])
vueApp.series = newSeries
```

**Comment by junedchhipa** [comment]
Yes, that's one of the correct ways to update the series.
Glad you found the workaround.
