### ISSUE TITLE
Fail to register component

### ISSUE THREAD

**Issue by yslai95** [apexcharts/vue-apexcharts#227]
I'm building an ElectronJS + VueJS + Typescript. It fails to register Apex Chart and having the issue 

`Unknown custom element: <apexchart> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

```
<template>
  <div> 
    <apexchart type="line" :height="height" :options="chartOptions" :series="series" />
  </div>
</template>

<script lang="ts"> 
import { mapGetters } from "vuex";
import apexchart from "vue-apexcharts";

export default {
  components: { apexchart },

```

package.json

    "apexcharts": "^3.18.1",
    "vue": "^2.6.11",
    "vue-apexcharts": "^1.5.0",

**Comment by dbsdenis** [comment]
Tenta:
`<template>
  <div> 
    <apexchart type="line" :height="height" :options="chartOptions" :series="series" />
  </div>
</template>

<script lang="ts"> 
import { mapGetters } from "vuex";
import chart from "vue-apexcharts";

export default {
  components: { apexchart: chart },`

**Comment by Emobe** [comment]
@dbsdenis can just be `import apexchart from "vue-apexcharts"` considering you are importing the default export, you can call it whatever you want
