### ISSUE TITLE
Y-Axis not updating

### ISSUE THREAD

**Issue by ZSharp1985** [apexcharts/vue-apexcharts#228]
I'm using the latest version of the vue-apexcharts component and when I update the chart options to change the 'max' on the y-axis it doesn't change on the UI. Am I missing something? I'm able to dynamically change the chart titles, data, and x-axis key without issue.

**Comment by dgaponov** [comment]
I found a solution to the problem. It is necessary to transfer chart options to computed property.
And in computed property return max via function.

Example
https://gist.github.com/dgaponov/84897b4adf5d05ebb6ec3f32fb74f159

**Comment by joaolisboa** [comment]
@dgaponov very simple fix which immediately fixed my issue. Thanks!
