### ISSUE TITLE
Updating annotations is broken since 2.1.6

### ISSUE THREAD

**Issue by johuhype** [apexcharts/vue-apexcharts#23]
We've got a chart options object:

<apexcharts class="apex-total-chart" type="area" :options="chartTotal.options" :series="chartTotal.series"></apexcharts>

this.chartTotal.options = {
...
annotations: { position: 'front', points: [] },
...
}

Prior to 2.1.6 we could add annotations dynamically using this.chartTotal.options.annotations.points.push(...)

this is not working anymore.

**Comment by junedchhipa** [comment]
The method you described above by pushing annotations is not the preferred way to add annotations.

I have introduced all the core ApexCharts method into Vue-component. So, please try calling `addPointAnnotation` method on the component.

<template>
  <div class="example">
    <apexcharts ref="chart" width="500" :options="chartOptions" :series="series"></apexcharts>
  </div>
</template>

<script>
  functionName: function() {
    this.$refs.chart.addPointAnnotation({ ... })
  },
</script>

Please have a look at the updated README to know how to call those methods.
Let me know if that worked.

**Comment by junedchhipa** [comment]
I also noticed that a `.hidden` class was added to annotations which was not removed on redrawing.
I have just fixed that - will be released in v2.2.1

**Comment by johuhype** [comment]
I just tried your addPointAnnotation suggestion. It is basically working, but how do I remove or clean the annotations this way?

Each time I make an update to the series either by 

this.chartTotal.series.push(totalChartSeries);
or
this.$apexcharts.exec('chart-total', 'updateSeries', [totalChartSeries]);

afterwards I am adding 2 annotations for the first and the max value:
this.$apexcharts.exec('chart-total', 'addPointAnnotation', { ... });

There is a date selector above my chartcontrol. Everytime the user changes the date and these two functions get called, annotations will not be cleared in the chart but they will overlap (leading to an impression of annotations getting bolder the more often a user changes dates). 

Plus, more annotations than I want are displayed:

Initial state
![image](https://user-images.githubusercontent.com/16450706/47984296-7b3cb780-e0d6-11e8-877e-3289e0f7f831.png)

Changing to 3M (last two annotations are not wanted)
![image](https://user-images.githubusercontent.com/16450706/47984304-7ed03e80-e0d6-11e8-9d70-1193537069ad.png)

Changing back to 1M (annotations appear now bolder)
![image](https://user-images.githubusercontent.com/16450706/47984313-87287980-e0d6-11e8-928b-5f6bf30c8bed.png)

**Comment by junedchhipa** [comment]
Hi @johuhype 

I tested the dynamic annotations and there are a couple of ways you can forceUpdate ApexCharts if you push annotations in `options.annotations.yaxis.push({ ... })` method.

So, the code becomes
```html
<apexchart ref="chart" type=line height=380 :options="chartOptions" :series="series" />
```

```javascript
this.chartOptions.annotations.yaxis.push({
  y: 8200,
  label: {
    text: 'Support',
  }
})

this.$refs.chart.updateOptions(this.chartOptions)
```

I also added `clearAnnotations()` method if someone wants to clear annotations externally

**Comment by johuhype** [comment]
got 2.2.1 now, unfortunately, there is a bug in the new clearAnnotations function:

      clearAnnotations: function clearAnnotations() {
        this.chart.clearAnnotations(options);
      }

either options need be passed or removed.

**Comment by junedchhipa** [comment]
Oops! Just fixed it.
Released v1.2.5

**Comment by junedchhipa** [comment]
Please note that only those annotations are removed which are added dynamically such as `this.$refs.chartContext.addPointAnnotation()` method. 

Annotations which are in config object will be removed but on next redraw() they will be visible again and redraw method gets the original config object.

**Comment by johuhype** [comment]
Unfortunately, I cannot confirm this. I am only adding annotations using 
this.$refs.charttotal.addPointAnnotation(...)

prior to adding them I call 
this.$refs.charttotal.clearAnnotations();

Nowhere else I am doing anything with the annotations. When I debug I can see that after clearAnnotations(), every annotations disappears, but as soon as I add one again, ALL previous cleared  annotations appear again.

**Comment by junedchhipa** [comment]
Ah! Interesting. Need to dig that. 
No worries, I got the issue, just need to implement a tiny fix for it. Thanks for your patience

**Comment by junedchhipa** [comment]
I just realized that while calling `addPointAnnotation()`, you can pass an argument `pushToMemory: false` to prevent preserving annotations in subsequent updates. By default, it is true - try turning it off.

`addPointAnnotation({ ... }, false)`

More info - https://apexcharts.com/docs/methods/#addpointannotation

Please try this and let me know if it fixes the issue

**Comment by johuhype** [comment]
Would like to try it, but it seems this parameter is not passed through from the vue component:

      addPointAnnotation: function addPointAnnotation(options) {
        this.chart.addPointAnnotation(options);
      },

**Comment by junedchhipa** [comment]
Ah! My bad. Need more `tests` 😀 
Just pushed a new release v1.2.6 with an additional parameter for annotations

**Comment by johuhype** [comment]
No problem :). Thanks for the new version. Now I can see the parameter getting passed.
However, if I set it to false, the annotation will not show at all. Even if I do not call clearAnnotations().

**Comment by junedchhipa** [comment]
Ok, I think - instead of spending more time on dynamic methods which are suitable for vanilla-js users, I need to find a way to directly handle it when the user changes the `annotations` property in the `options` object. 

Although, these methods should work independently, so I will fix them too when I get time to test them thoroughly. 
I will be back with some updates in a few days.

Thanks

**Comment by junedchhipa** [comment]
@johuhype I just tested annotations by updating the `chartOptions` prop and it works well. 
Here is the codesandbox demo - https://codesandbox.io/s/xrkpv1n65o

I think, instead of pushing annotations to the array, it is better you try it this way by updating `chartOptions` directly.

**Comment by johuhype** [comment]
Yes its working this way. But all the other previously set chartOptions get lost (as seen in VueDevtools). 
This does not seem to matter to the apex component right now. 

Using the spread operator its possible to keep the existing options anyway in merging the two objects:

                    this.chartTotal.options = {...this.chartTotal.options, ...{
                        annotations: {
                            points: annoPoints
                        }
                    }};

Dont know but I think there should be an easier way to do this.

**Comment by junedchhipa** [comment]
Yes, assigning new options directly will overwrite the object (as seen in VueDevTools), although it doesn't affect ApexCharts as ApexCharts stores the old options internally.

Using the spread operator is also a valid way of merging the new options with the existing one. There are other several ways, it comes down to preference.
There is a React-ApexCharts video by Traversy Media on Youtube - https://www.youtube.com/watch?v=JxEyXOlSgV0&t=1600s which updates the options using spread operator. So, I don't think - it's very unusual way of dealing with it.

**Comment by junedchhipa** [comment]
Closing this, as I see no better alternative to handle nested options updates.
