### ISSUE TITLE
Yaxis negative values reverse

### ISSUE THREAD

**Issue by duka94** [apexcharts/vue-apexcharts#230]
When you have just negative value in y chart, you cant reverse yaxis values, you just can reverse area of chart. In previous versions that functionality worked.

**Comment by junedchhipa** [comment]
Can you please elaborate what's the exact issue and what was working before?
A codepen will be helpful.

**Comment by duka94** [comment]
@junedchhipa Sorry for a long away period. 

I'm created [codepen](https://codepen.io/duka4/pen/dyGdYQy)

I need functionality to switch green and white areas (to be the opposite). In the previous version, I was able to do that but in the newest, I can't.
