### ISSUE TITLE
Cant update yaxis max value dynamically

### ISSUE THREAD

**Issue by MarcelFranken** [apexcharts/vue-apexcharts#233]
Hi,

i have a component which shows a dynamic count of apexcharts.
So i have apexcharts inside a v-for loop, with the following properties set:
```javascript
<apexchart type="area" height="255" :options="oChartOpt[`${sOsname}`]" :series="oChartData[`${sOsname}`]"></apexchart>
```
where `sOsname` comes from `v-for="sOsname in ..."`

in my data i have defined:
```javascript
return {
            oChartData: {},
            oChartOpt: {}
        }
```
The data will then be defined on my mounted function:

```javascript
for (sOsname of ...) {
  var oTempChartData = cloneDeep(this.oImportancyChartData[sOsname])
  var oTempChartOpt = cloneDeep(this.oImportancyChartOpt[sOsname])
  this.$set(this.oChartOpt, sOsname, oTempChartOpt)
  this.$set(this.oChartData, sOsname, oTempChartData)
}
```
this.oImportancyChartOpt comes from a mapGetter computed value (vuex store)
Everything works fine! Options and Data are passed and shown as i want it.

But if i change my vuex state (via mutation) to something like this (just an example):
```javascript
this.oImportancyChartOpt[sOsname]['yaxis']['max'] = 6000
```
and rerun my 
```javascript
var oTempChartOpt = cloneDeep(this.oImportancyChartOpt[sOsname])
  this.$set(this.oChartOpt, sOsname, oTempChartOpt)
```
nothing happens.

I see a animation on my chart, but the max value is still the old one.
Can someone help me?

**Comment by MarcelFranken** [comment]
After some tests i found out that i have the same problem as described in #228

**Comment by dgaponov** [comment]
I found a solution to the problem. It is necessary to transfer chart options to computed property.
And in computed property return max via function.

Example
https://gist.github.com/dgaponov/84897b4adf5d05ebb6ec3f32fb74f159

**Comment by gbellini79** [comment]
Same here using version 3.22.2.
If I set the Y axis min and max directly it doesn't works:
```
this.chartOptions.yaxis[0].min = this.min;
this.chartOptions.yaxis[0].max= this.max;
this.chartChart.updateOptions(this.chartOptions);
```

Instead it works if in the initial chartOptions object I use:
```
yaxis: {
  min: () => this.min,
  max: () => this.max,
}
```

Is this the intended behavior? The first method was working in version 3.15.5.
