### ISSUE TITLE
VueApexChartsComponent typing not exported

### ISSUE THREAD

**Issue by donqstepper** [apexcharts/vue-apexcharts#234]
Hi, I am using ApexCharts in a TypeScript Vue application and it is very impressive. However, I have a chart that I want to append data to. So I have got a `ref` to the chart component, and want to type it with the VueApexChartsComponent interface provided in the typings. However, that interface is not exported, so I cannot import it into my code.

Am I missing something obvious about how I am supposed to use this?

https://github.com/apexcharts/vue-apexcharts/blob/master/typings/vue-apexcharts.d.ts

reproduction code:
```typescript
import { VueApexChartsComponent } from "vue-apexcharts"
```

**Comment by davidalpert** [comment]
the `VueApexChartsComponent` interface in that file is defined but not exported, so it is unavailable for use in client code.

it would need to be exported in order for me to use it in my code.

**Comment by davidalpert** [comment]
@junedchhipa I have opened #386 as I believe that it will resolve this issue.

**Comment by itsamaik** [comment]
@junedchhipa Could you publish a new version of this package so this change will become available? Thank you
