### ISSUE TITLE
Can't dynamic change xaxis min & max

### ISSUE THREAD

**Issue by syue1126** [apexcharts/vue-apexcharts#238]
Hello,

I want to dynamic change xaxis min & max base on data's date (add/minus some day), but it seems to ignore that setting. 

[sample code like this](https://codepen.io/ming-syue/pen/pojZPjy)

Thx

**Comment by felipechiodini** [comment]
to update options of the charts without the method "uptadeOptions()" you need try like this:
`        
this.chartOptions = { ...this.chartOptions, ...{
                xaxis: {
                    min: moment(data1).add(-7, 'day').valueOf(),
                    max: moment(data2).add(7, 'day').valueOf()
                }
          } };
`

**Comment by syue1126** [comment]
I try to use this method to update chartoptions, but xaxis min & max still not set currently

[sample code](https://codepen.io/ming-syue/pen/pojZPjy)

**Comment by felipechiodini** [comment]
I get what you say,

The xaxis is set automatic, so, if you wanna put null values in timeline you need try [this](https://apexcharts.com/vue-chart-demos/line-charts/null-values/).

just provide timestamps in series[x].data you get the xaxis, and like I saw, if you want time without points you pass "null" in value point
