### ISSUE TITLE
Error: <rect> attribute height: A negative value is not valid. ("-64")

### ISSUE THREAD

**Issue by NegativeDearc** [apexcharts/vue-apexcharts#25]
if not give the prop of "width", plot can't be show correctly.

**Comment by junedchhipa** [comment]
Can you please create a codepen? As I can't reproduce this issue on my side.

**Comment by NegativeDearc** [comment]
Well yes I'll post code later(not sure how to use codepen) but let me explain what I'm doing firstly.

I'm using apexcharts for user profile component which is a full-screen dialog usually hidden but will be opened when click the user icon button,  then will achieve data by axios.

**Comment by junedchhipa** [comment]
Not sure if it is related with full-screen dialog.
But, I understood your point. If the chart tries to draw in a 0 width element, it will throw this error. You can try rendering the chart only when the dialog is open.

If you can try forking this [Vue template](https://codesandbox.io/s/voyy36o7y) of code-sandbox and reproduce the issue, I can look more.

**Comment by labtocat** [comment]
@junedchhipa Is there a way to dynamically set the width if not set? What I do at the moment is a kind of temp fix always adjusting the width as the number of data pair increase.

**Comment by junedchhipa** [comment]
@labtocat `width: 100%` doesn't works? Where are you setting the width? In ApexCharts prop or in CSS?

**Comment by junedchhipa** [comment]
Closing due to lack of response

**Comment by yxxa** [comment]
hy, i got same error
i use this chart https://github.com/apexcharts/apexcharts.js
like the first example of chart here https://apexcharts.com/docs/creating-first-javascript-chart/

the problem is trow a error like a image i have, chart not displayed in first page load
if i resizing viewport width, chart is showing xD
can u help me?

![image 74](https://user-images.githubusercontent.com/25668079/48879955-c7ab2580-ee40-11e8-8962-16ebfdeb8098.png)

**Comment by yxxa** [comment]
> @labtocat `width: '100%'` doesn't works? Where are you setting the width? In ApexCharts prop or in CSS?

in my css, width parent of #chart 100% also, and already set width and hight of #chart like https://codepen.io/apexcharts/pen/xYqyYm
i just test with single file, and its work fine
the error is displayed in my current project i have, but why?
im confused xd

**Comment by labtocat** [comment]
@junedchhipa sorry for late response. It didn't work

**Comment by junedchhipa** [comment]
I tested Vue-ApexChart component in a `v-if` condition and it fails to render even if `v-if` is set on the parent element of `<apexchart>`. Currently `<apexchart>` expects even the parent element to be present along with it to calculate the width correctly.

I will find a solution for this - but for now make sure you wrap `<apexchart>` in a parent element which not have `v-if` attached to it or hidden by any other means.

If you need to hide the chart, set `v-if` to the grandparent of the `<apexchart>`
