### ISSUE TITLE
xaxis categories array  don't update with new data array in  apex bar chart 

### ISSUE THREAD

**Issue by sinchanpokemon** [apexcharts/vue-apexcharts#251]
how can we update chartOptions.axis.categories value after new data array

**Comment by lampewebdev** [comment]
We are facing the same problem right now with bar charts.

Even after replacing the `options` and `series` object.

For example, if we have category: [x,y] and then show [x,y,z] and then remove z we still see [x,y,z]

**Comment by junedchhipa** [comment]
I recommend using the below series format to avoid updating series and categories separately. Skip the categories in `xaxis.categories`.


```javascript
series: [{
  data: [{
    x: 'category1',
    y: 20
  }, {
    x: 'category2',
    y: 30
  },{
    x: 'category3',
    y: 50
  }]
}],
xaxis: {
  categories: []
}
```

Now, when you update the `series.data`, only the `updateSeries` function will be called.
