### ISSUE TITLE
Download CSV in hamburger menu disappears after building the app

### ISSUE THREAD

**Issue by Alessandro-Cor** [apexcharts/vue-apexcharts#255]
During development, I can see the whole toolbar and the option to download as CSV 

![image](https://user-images.githubusercontent.com/56913968/86214760-deb50c00-bb7b-11ea-863f-2e6b79833f31.png)

When I build my app though, the toolbar disappears completely and I can't download data as CSV anymore 

![image](https://user-images.githubusercontent.com/56913968/86214826-fab8ad80-bb7b-11ea-8a3e-7c6d114a412b.png)

This happens on multiple charts, altough only on one chart the whole toolbar disappears (on the others it is still present, but I still don't have the option "download CSV")

**Comment by junedchhipa** [comment]
That's very strange.
Which version of apexcharts are you using?

**Comment by Alessandro-Cor** [comment]
> That's very strange.
> Which version of apexcharts are you using?

Hi, I'm using apexcharts 3.6.12 and vue-apexcharts 1.3.5 

The weird thing is that I don't have this problem in earlier versions of the app, I didn't update any dependency or change significant parts of the code so I really don't know what the problem could be

**Comment by junedchhipa** [comment]
Can you try upgrading to the latest version (3.193) and see if it fixes the issue?

**Comment by junedchhipa** [comment]
Btw, CSV export won't work in an irregular multiple data-series where the x-values of one series is different than the other.
For eg.,
```javascript
series: [{
  name: 's-1',
  data: [{
    x: new date('2018-01-02').getTime(),
    y: 10
  }, {
    x: new date('2018-01-03').getTime(),
    y: 20
  }]
}, {
  name: 's-2',
  data: [{
    x: new date('2018-02-02').getTime(),
    y: 10
  }, {
    x: new date('2018-02-04').getTime(),
    y: 20
  }]
}]
```
This is a limitation that hasn't been addressed yet.

**Comment by Alessandro-Cor** [comment]
Thanks for your reply! I actually found the problem. I had to remove all "^" from my package.json files in order to avoid breaking things, I just had to put it back only on apexcharts and vue-apexcharts and everything is fixed. 

This also explains why it used to work in the past
