### ISSUE TITLE
Locale settings doesn't work

### ISSUE THREAD

**Issue by Insiderto** [apexcharts/vue-apexcharts#26]
Can't set locale settings in vue-apexcharts component.
```
import ru from "apexcharts/dist/locales/ru.json";

chartOptions: {
 locales: [ru],
 defaultLocale: "ru",
}
```

**Comment by Insiderto** [comment]
My bad, right settings is 

```
import ru from "apexcharts/dist/locales/ru.json";

chartOptions: {
chart: {
  locales: [ru],
 defaultLocale: "ru",
 }
}
```

**Comment by robsontenorio** [comment]
@junedchhipa Such locale folder does not exists 

```
import ru from "apexcharts/dist/locales/ru.json";
```

error
![Captura de Tela 2019-05-25 às 15 12 42](https://user-images.githubusercontent.com/118955/58373145-a4e8ef00-7eff-11e9-9c3f-3ca61b07bfd0.png)

node modules
![Captura de Tela 2019-05-25 às 15 13 01](https://user-images.githubusercontent.com/118955/58373147-a9150c80-7eff-11e9-9f34-e5b1dbb211fd.png)

**Comment by junedchhipa** [comment]
Thanks for the catch.
Just fixed the issue. Will be available in the next release.
