### ISSUE TITLE
Panning is not smooth when chrome dev tools is open

### ISSUE THREAD

**Issue by fabien-ml** [apexcharts/vue-apexcharts#261]
Hello,

I found a weird issue when trying to use the pan tool.
When the Chrome DevTools is open the horizontal scrolling behavior of the pan is not smooth.

Step to reproduce : 
1. Create a chart
2. Zoom in the chart
3. Open Chrome dev tools
4. Try use the pan tool
5. The horizontal scrolling behavior is not smooth
6. Close Chrome dev tools
7. Try use the pan tool again
8. It work as expected

**Comment by junedchhipa** [comment]
Panning is a very resource-intensive functionality that updates the chart several times in a single second. So, keeping developer tools open will multiply the intensity as each chart update reflects in the developer tools too.
