### ISSUE TITLE
Incorrect work in Mixed Charts and enabled stacked mode when I.m trying use more than one line chart

### ISSUE THREAD

**Issue by sleleko** [apexcharts/vue-apexcharts#263]
Hello! Incorrect work in Mixed Charts when I.m trying use more one line chart.

First line rendered correct, column 1, column 2, column 3 rendered.

But when I,m change type of data for "column2" from column to line I'ts rendering is incorrect and placed over other charts.

How fix it?
 Please see https://codesandbox.io/s/possible-bug-apexcharts-qyqnu?file=/src/App.vue .

Blue line is rendering incorrect

**Comment by junedchhipa** [comment]
Please create a working codepen example so that it can be easily reproduced.

**Comment by sleleko** [comment]
> Please create a working codepen example so that it can be easily reproduced.

Ok! But how I can connect parent and child component on codepen? It's passible ?

**Comment by sleleko** [comment]
> Please create a working codepen example so that it can be easily reproduced.

@junedchhipa Hi! I,m created example with bug https://codesandbox.io/s/possible-bug-apexcharts-qyqnu?file=/src/App.vue

**Comment by sleleko** [comment]
Blue line in rendered incorrect

**Comment by sleleko** [comment]
Hello again @junedchhipa ! Today I,m get example from your site, added to it second line and we have this bug https://codesandbox.io/s/possible-bug-apexcharts-second-variant-fxzzf?file=/src/components/test.vue
