### ISSUE TITLE
ReferenceError: ApexCharts is not defined

### ISSUE THREAD

**Issue by alexeyvokin** [apexcharts/vue-apexcharts#27]
Screenshot of error:
![image](https://user-images.githubusercontent.com/15310384/48766055-2314d080-ece6-11e8-9a5b-852415525d91.png)

Dependencies:
```
...

"apexcharts": "^2.2.1",
"vue-apexcharts": "^1.2.6"
```

An error appears when using brush-parameter for line graphs. I am trying to adapt the code for the SPA, which lies [here](https://github.com/apexcharts/apexcharts.js/blob/master/samples/vue/line/brush-charts.html).

I import the VueApexCharts library in single page component as:
```
import VueApexCharts from 'vue-apexcharts'
```

and use it, as:
```
...

components: {
   apexcharts: VueApexCharts,
},

...
```

and in template:
```
...

<apexcharts type="line" height="230"
    :options="chartOptionsArea"
    :series="series"
></apexcharts>
<apexcharts type="area" height="130"
   :options="chartOptionsBrush"
   :series="series"
></apexcharts>

...
```

chartOptionsArea, chartOptionsBrush and series params copied from file by link

UPD: If delete brush-parameter, the graphics are displayed normally.

**Comment by junedchhipa** [comment]
After importing VueApexCharts, can you try registering component globally?
```javascript
Vue.component('apexcharts', VueApexCharts)
```

**Comment by alexeyvokin** [comment]
@junedchhipa yes, it does not solve the problem. You can try to imitate it.

**Comment by junedchhipa** [comment]
@alexeyvokin Ok, reproduced the issue on my side.
Weird, it works in browser (as it works in samples) - but fails in Vue environment.

I will look into it.

**Comment by junedchhipa** [comment]
Fixed it. Please use the latest version `vue-apexcharts@1.2.7`
Here is the full example on codesandbox - https://codesandbox.io/s/voyy36o7y

**Comment by alexeyvokin** [comment]
@junedchhipa thank you, this solved the problem.
