### ISSUE TITLE
Chart options are not reactive

### ISSUE THREAD

**Issue by lukasleitsch** [apexcharts/vue-apexcharts#28]
The readme says that the chart option are reactive and will be update after changing it.

https://codepen.io/lukasleitsch/pen/NEyZGd

In this usecase the updating of the annotations not working. (Update Annotation Button) In the console you see the updated chart options object.

If I use the the updateOptions function the updating of the options works, (Force Update Annotation Button)

I guess that the first version should also work, shouldn't it?

**Comment by junedchhipa** [comment]
While updating the nested props, you should use something like spread operator to preserve existing options

So, instead of `this.options.annotations = {...}`, you should do

```javascript
this.options = {...this.options, ...{
    annotations: {
        ...
    }
}}
```

That should fire the Vue watcher and the chart will re-render

**Comment by lukasleitsch** [comment]
Ohh, yes. You are right. I forgot that only the first level in an object is reactive. Thanks for your example.

Yes, an example in the readme would be great.

Should be the issue keep open until you added an example in the readme?

**Comment by junedchhipa** [comment]
Updated README

**Comment by nickgayo12** [comment]
Anyone can help me, I am trying to update the labels under chartOptions? I also followed the syntax on how to update second-level objects, but it says warning. Here's my code:

this.chartOptions = {...this.chartOptions, ...{
    labels: {
         ...this.allodata[i].stock_id
    }
}}

Thank you for helping me :)

**Comment by codenamezjames** [comment]
Here is what i did.. easy copy paste if you have a similar issue or your using quasar :)
```
watch: {
    '$store.state.layouts.theme' () {
      this.chartOptions = { ...this.chartOptions, colors: [colors.getBrand('secondary'), colors.getBrand('primary')] }
    }
  }
```

**Comment by guestisp** [comment]
@junedchhipa could you please make a sample on how to change a single value without having to overwrite the full object ?

In example, I would like to change the value of `y2` from here:

```
options: {
   annotations: {
      yaxis: [
         {
            .....some things ......
            y2: I HAVE TO CHANGE THIS
         }
      ]
   }
}
```
