### ISSUE TITLE
hideSeries does not function as described

### ISSUE THREAD

**Issue by rbclark** [apexcharts/vue-apexcharts#285]
Based on the documentation on the README and https://apexcharts.com/docs/methods/#hideSeries my understanding of hideSeries is that it provides the user with a way to hide a series of data programmatically. I have tried to reproduce this behavior using the following simple jsfiddle: https://jsfiddle.net/r38dxu7g/2/ and it seems that instead of hiding a series of data it just raises the following error:

```
TypeError: t is undefined
```

I am seeing the same behavior when attempting to use this in my Vue application. Am I just doing something wrong? Thank you in advance for any insight you can provide.

**Comment by junedchhipa** [comment]
Fixed in this [commit](https://github.com/apexcharts/apexcharts.js/commit/edfff0b1545e88482b23efcd62e760261f08f0e0)

A new version will be released soon.
