### ISSUE TITLE
Custom interval for yaxis

### ISSUE THREAD

**Issue by TomDeSmet** [apexcharts/vue-apexcharts#29]
Hi,

is it possible to set a custom interval for the yaxis?

I have a chart with values ranging between 100 and 145. The yaxis values seem to be generated automaticaly based on the chart values, which is great. But that renders yaxis values with decimals and none rounded values.
E.g. there are values such as 137 or 120.5 and those look weird on a chart.

Is it possible to set it to a range (and plot the chart accordingly) such as:
100 - 105 - 110 - 115 - 120 - 125 - 130 - 135 - 140 - 145
So rounded numbers with an interval of 5.

**Comment by junedchhipa** [comment]
Try this

```javascript
yaxis: {
    min: 100,
    max: 145,
    tickAmount: 9
}
```
Live example - https://codepen.io/apexcharts/pen/qQMrXL

If you want to avoid decimal values in yaxis ticks, you can set `yaxis.labels.formatter`
```javascript
yaxis: {
    labels: {
      formatter: function(val) {
        return val.toFixed(0)
      }
    }
}
```

**Comment by TomDeSmet** [comment]
Great! I already tried with tickAmount, but I set it to 10 which of course doesn't make sense now I understand how it works.

**Comment by Naren-hybreeder** [comment]
@junedchhipa  Can you help me in this issue? https://github.com/apexcharts/apexcharts.js/discussions/3015
