### ISSUE TITLE
Bug. Mixed chart doesn't show end data labels

### ISSUE THREAD

**Issue by enmalafeev** [apexcharts/vue-apexcharts#290]
I have a mixed bar chart with columns and line. See the [codesandbox exapmle](https://codesandbox.io/s/mixedchart-doesnt-show-last-datalabels-w6g5z?file=/src/components/Chart.vue). I set:
```plotOptions: {
        bar: {
          columnWidth: "100%",
          dataLabels: {
            position: "top",
            hideOverflowingLabels: false,
          },
        },
      },
      dataLabels: {
        enabled: true
       }
    }
```
And I'm supposed to see all the data labels. But after render apexcharts truncates the outermost data labels and doesn't display them.(See the screenshot). It is a bug. 
If I change ` plotOptions: {
        bar: {
          columnWidth: "20%"}`. Apexcharts show all data labels.

![clolumnWidth100](https://user-images.githubusercontent.com/26414215/96988480-10881f00-152d-11eb-92bd-4d0fe2fb8c9c.png)
![columnWidth20](https://user-images.githubusercontent.com/26414215/96988494-14b43c80-152d-11eb-9a86-6ad4180434b6.png)

**Comment by xoctuchan** [comment]
hello good night,
I have the same problem, did you solve it?
