### ISSUE TITLE
apexcharts.min.js?3d1e:6 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by andyslack** [apexcharts/vue-apexcharts#293]
Hi Guys,

I have been banging my head against this for a while now.

I am pulling data in from an API and updating the charge on the fly

`<vue-apex-charts
        type="area"
        height="350"
        :options="chartOptions"
        :series="series"
      ></vue-apex-charts>`

Here is the output for the series

```
console.log(JSON.stringify(series))

[{"name":"Testogen","data":[108,107,126,121,42,23,27,23,35,48,36,38,37,34,0,0,0,0,0,0,0,0,0,0]},{"name":"Viasil","data":[1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},{"name":"Blackwolf","data":[12,15,16,10,7,1,7,0,4,8,10,10,7,5,0,0,0,0,0,0,0,0,0,0]},{"name":"PhenGold","data":[2,3,1,3,1,4,0,2,1,1,3,3,2,15,0,0,0,0,0,0,0,0,0,0]},{"name":"BrutalForce ","data":[30,46,38,30,21,10,12,12,25,47,14,7,17,21,0,0,0,0,0,0,0,0,0,0]},{"name":"MaleExtra GBP","data":[0,2,0,0,0,0,0,1,0,0,2,1,0,3,0,0,0,0,0,0,0,0,0,0]},{"name":"Immune Defence ","data":[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0]}]
```

Here is the output for the series

```
console.log(JSON.stringify(this.chartOptions))

{"grid":{"show":true,"padding":{"left":0,"right":0},"borderColor":"rgba(0,0,0,0.1)"},"tooltip":{"theme":"dark"},"chart":{"stacked":true,"toolbar":{"show":false}},"colors":["#2aae7d","#101010","#c0af92","#000000","#004168","#4f4e4e","#225b41"],"fill":{"type":"solid","color":["#2aae7d","#101010","#c0af92","#000000","#004168","#4f4e4e","#225b41"]},"dataLabels":{"enabled":false},"stroke":{"curve":"straight","width":0},"markers":{"size":0},"xaxis":{"categories":["23 Hours Ago","22 Hours Ago","21 Hours Ago","20 Hours Ago","19 Hours Ago","18 Hours Ago","17 Hours Ago","16 Hours Ago","15 Hours Ago","14 Hours Ago","13 Hours Ago","12 Hours Ago","11 Hours Ago","10 Hours Ago","9 Hours Ago","8 Hours Ago","7 Hours Ago","6 Hours Ago","5 Hours Ago","4 Hours Ago","3 Hours Ago","2 Hours Ago","1 Hour Ago","Last Hour"],"show":false,"labels":{"show":false},"convertedCatToNumeric":true},"yaxis":{"labels":{"style":{"cssClass":"text-muted fill-color"}}}}
```

I feel like im missing something obvious but I cannot figure it out. 

Screenshots:

<img width="895" alt="Screenshot 2020-11-17 at 19 31 22" src="https://user-images.githubusercontent.com/3747768/99431755-894f8080-290b-11eb-897f-73b9f71c270c.png">

<img width="769" alt="Screenshot 2020-11-17 at 19 31 40" src="https://user-images.githubusercontent.com/3747768/99431759-8a80ad80-290b-11eb-807a-13117d9d9acd.png">

Any help would be appreciated.

**Comment by junedchhipa** [comment]
Can you try loading [an un-minified version of ApexCharts](https://cdn.jsdelivr.net/npm/apexcharts@3.22.2/dist/apexcharts.js) so we can see what exactly is the error?

**Comment by junedchhipa** [comment]
It also seems like your chartConfig is missing chart type.

```js
chart: {
  type: 'line'
}
```

**Comment by andyslack** [comment]
> Can you try loading [an un-minified version of ApexCharts](https://cdn.jsdelivr.net/npm/apexcharts@3.22.2/dist/apexcharts.js) so we can see what exactly is the error?

Sorry @junedchhipa, stupid question but how do I import the un-minifed version in my vue.js component?

**Comment by andyslack** [comment]
Any help on the above would be appreciated

**Comment by andyslack** [comment]
Actually it looks like the bug has been fixed. Thank you.

**Comment by deepak-briks** [comment]
> Actually it looks like the bug has been fixed. Thank you.

how did you fix it?

**Comment by valeri** [comment]
I have similar problems when I need two different charts(bar, line) and I use v-if, But this error not showing when I used v-show.

**Comment by ognitio-technologies** [comment]
Its showing the same error
![Uploading Screenshot 2022-11-18 at 10.10.36 PM.png…]()

**Comment by aniket-pande** [comment]
Facing the same issue

**Comment by Tapmeet** [comment]
How did you fix this @andyslack. Answer would be greatly appreciated. Many thanks

**Comment by molaei2000** [comment]
Just update apexcharts to latest version
