### ISSUE TITLE
Updating the charts is very slow

### ISSUE THREAD

**Issue by tol64** [apexcharts/vue-apexcharts#296]
@junedchhipa 

[Beginning of discussion](https://github.com/apexcharts/vue-apexcharts/issues/208)

> Make sure you have these things disabled to maximize performance
> 
> Animation chart.animations.enabled = false
> Markers size set to 0 markers.size = 0
> Disable DataLabels dataLabels.enabled = false

Unfortunately, these recommendations did not work. Updating the charts is very slow. And the more charts in the window, the more delay. But this should not apply to properties such as text colour. 

It is necessary to optimise the code in the sources of the library.

The code for playback:

```
...
this.chartOptions = {
    chart: {
        foreColor: textColor
    }
};
...
```

Create several different types of charts and just try to update them.

**Under the same conditions, Chart.js charts are updated approximately 10 times faster!**

I prepared a minimal project to reproduce and find out why the library is so slow:

- [testnuxt.zip](https://github.com/apexcharts/vue-apexcharts/files/5579625/testnuxt.zip)

**Comment by tol64** [comment]
Have you already tried the tests? Have you replayed the problem?

**Comment by DMOAbove** [comment]
Same problem here... super super slow takes almost 1sec to run the update

**Comment by CreativeWarlock** [comment]
8 seconds to render a chart with roughly 1500 dates. This is incredible...
