### ISSUE TITLE
TypeError: this.$apexcharts.updateOptions is not a function

### ISSUE THREAD

**Issue by tol64** [apexcharts/vue-apexcharts#298]
The third day I try to find out the reason for the extremely slow update of the charts' properties: https://github.com/apexcharts/vue-apexcharts/issues/296

Now I decided to try to update the properties directly through the **UpdateOptions**() method, but this time I ran into another error:

`this.$apexcharts.updateOptions is not a function`

![image](https://user-images.githubusercontent.com/50295805/99983379-d6749c00-2dbc-11eb-9258-bd5ecb8d4f19.png)

![image](https://user-images.githubusercontent.com/50295805/99983456-ed1af300-2dbc-11eb-80a1-5c0ce39d1e09.png)

**Comment by LongGiang-code** [comment]
same problem here anyone got any solutions yet?
