### ISSUE TITLE
Selection breaks when v-if on brush chart

### ISSUE THREAD

**Issue by OlivierRiberi** [apexcharts/vue-apexcharts#30]
Hi,

I got this error when I try to do a v-if on a graph with brush option:
Cannot read property 'destroy' of null
![screen shot 2018-11-27 at 15 51 30](https://user-images.githubusercontent.com/4389209/49119596-c709f900-f25d-11e8-97d7-7b69e70b8797.png)

It breaks the navigation on the brush chart.

I'm using:
```
"apexcharts": "2.2.2",
"vue-apexcharts": "1.2.7"
```
Please click the Toggle button twice on the [Codesandbox](https://codesandbox.io/s/nwo480wxjl)
(I reused your code from another issue. I only added this Toggle button on App.vue)

**Comment by junedchhipa** [comment]
Please update `apexcharts` to v2.2.3 to prevent the `destroy` error.
If you get another error `setAttribute` on undefined - I am working on it
