### ISSUE TITLE
Adding "categories" of "xaxis" does not respond.

### ISSUE THREAD

**Issue by kolla121** [apexcharts/vue-apexcharts#31]
before:
{"type":"category","categories":["20181101","20181102","20181103","20181104","20181105","20181106","20181107","20181108","20181109","20181110","20181111","20181112","20181113","20181114","20181115","20181116","20181117","20181118","20181119","20181120","20181121","20181122","20181123","20181124","20181125","20181126","20181127","20181128","20181129","20181130"]}

after : 
{"type":"category","categories":["201810","201811"]}

I changed the "categories" value, but the graph does not respond.

vue devtool
![image](https://user-images.githubusercontent.com/38930666/49147112-209a2280-f347-11e8-82cf-e74f3b3b95db.png)

web
![image](https://user-images.githubusercontent.com/38930666/49147164-4293a500-f347-11e8-9548-c64cb946d933.png)

**Comment by junedchhipa** [comment]
The update works as expected.

Make sure you update the whole object instead of updating the nested property as specified in the README



**Important:** While updating the options, make sure to update the outermost property even when you need to update the nested property.

✅ Do this
```javascript
this.chartOptions = {...this.chartOptions, ...{
    xaxis: {
        labels: {
           style: {
             colors: ['red']
           }
        }
    }
}}
```

❌ Not this
```javascript
this.chartOptions.xaxis = {
    labels: {
        style: {
          colors: ['red']
        }
    }
}}
```
