### ISSUE TITLE
x-axis label color not changing.

### ISSUE THREAD

**Issue by rawheel** [apexcharts/vue-apexcharts#313]
![image](https://user-images.githubusercontent.com/47301347/104137576-afe7e000-53bf-11eb-8ead-4c92dae29076.png)
![image](https://user-images.githubusercontent.com/47301347/104137582-bc6c3880-53bf-11eb-8a6a-9cd2d2a33849.png)

**Comment by junedchhipa** [comment]
You don't need to use an array if you aren't targeting individual x-axis label.
Just pass a string

xaxis: {
  labels: {
    style: {
      colors: '#fff'
    }
  }
}
