### ISSUE TITLE
How to fire zoom on button click?

### ISSUE THREAD

**Issue by kentforth** [apexcharts/vue-apexcharts#314]
I have Line Chart. There are plus and minus buttons that can increase or descrease chart.

I want to have same functionality on my custom buttons;

If I run method `increaseZoom()` that chart should be zoomed in and I f I run method` descreaseZoom()` that chart should be zoomed out

**How can I do it?**

```
chartOptions: {
chart: {      
        zoom: {
          enabled: true,
          type: 'x'
        }
      }
}
```

**Comment by rolandgvc** [comment]
Any updates on this?
