### ISSUE TITLE
After zooming in to max level and resetting the chart by clicking on home button breaks chart

### ISSUE THREAD

**Issue by rojeenam** [apexcharts/vue-apexcharts#315]
Issue Demo:
https://apexcharts.com/vue-chart-demos/area-charts/spline/

Reproduce:
  1.  Click on the zoom in button, till max zoom level
  2.  Click on the reset button
  3.  After the chart is set to original state click on the zoom again, it will be set to max zoom level

Expected Behavior:
The zoom level should also reset after the chart goes to original state

**Comment by LukeLaScala** [comment]
Also having this issue. Just clicking the reset button breaks the chart, no matter what view the chart was in when clicked.

**Comment by junedchhipa** [comment]
I cannot see the issue. Can you confirm if it still happens with the latest version-3.24.0?

**Comment by oriolnadal** [comment]
I am using version 3.27.3 and I am also getting the same error.

**Comment by jasonwiesner** [comment]
Im getting a cannot ready property x of undefined when trying to zoom the x axis by clicking and highlighting a portion. The whole chart disappears.

**Comment by robclancy** [comment]
Having this issue today and seeing it open since the start of 2021 isn't very reassuring.

**Comment by robclancy** [comment]
Reopen this wtf
