### ISSUE TITLE
Problem with the element foreignObject containing legend

### ISSUE THREAD

**Issue by jcfauchet** [apexcharts/vue-apexcharts#32]
There is a problem with the element foreignObject containing legend that comes in front of chart element.
![capture](https://user-images.githubusercontent.com/21689610/49700288-f06f4100-fbdc-11e8-8beb-ef237e12c536.JPG)
![sans-titre-1](https://user-images.githubusercontent.com/21689610/49700335-81deb300-fbdd-11e8-8005-b80fed5845a8.jpg)

Because this elements is positionned after the chart element, we can't catch hover event to display tooltip and catch click on bar's of chart because this element has same height than global chart.

**Comment by junedchhipa** [comment]
Ouch! Thanks a lot for catching that.
I made a major rewrite for legend today and missed this part.

I will do a patch release very soon

**Comment by jcfauchet** [comment]
@junedchhipa Perfect, works well now, thx ! :+1:
