### ISSUE TITLE
Updating options on a synchronized chart updates options of all charts

### ISSUE THREAD

**Issue by nbst84** [apexcharts/vue-apexcharts#322]
If charts A and B are synchronized, updating the title of chart A will also update the title of chart B.

See: https://codepen.io/nicolasbrigodiot/pen/bGBqevv

**Comment by vano20** [comment]
Happen to me, I need to show a chart based on user selected chart, when the selected chart changed, options from selected chart that doesn't exist on the other chart suddenly get assigned.

**Comment by frufin** [comment]
This happened because you mutated directly your chart options.
You should instead use the updateOptions() method, setting the 4th parameter (updateSyncedCharts) to false.
