### ISSUE TITLE
Typescript with vue-apexcharts

### ISSUE THREAD

**Issue by adpeyre** [apexcharts/vue-apexcharts#33]
Hi,

Is it possible to add types to use vue-apexcharts with Typescript ?

**Comment by junedchhipa** [comment]
I have provided typings in the core ApexCharts repository.
https://github.com/apexcharts/apexcharts.js/blob/master/apexcharts.d.ts

Are separate types for vue-apexcharts required still?
I do not have much experience in typescript, so a PR is welcome  🙈

**Comment by steebchen** [comment]
@junedchhipa Yes, because typescript searches only for types for vue-apexhcarts. You would need to add a "typings" field in the package.json of this project to a new .d.ts file, just like in apexcharts.js. From there, you should add the Vue plugin typings (sadly I never wrote a vue plugin so I don't know how to do this step either) and then you can then just reference the original typings like `ApexCharts` from apexcharts.

**Comment by divinespear** [comment]
Inspired by @dror-weiss, I enhanced declaration like this, in single file.

**vue-apexcharts/index.d.ts**:
```
declare module 'vue-apexcharts' {
  import Vue from 'vue';
  import ApexCharts, { ApexOptions } from 'apexcharts';

  interface VueApexCharts extends Vue {
    // data
    readonly chart?: ApexCharts;
    // props
    options?: ApexOptions;
    type?: 'line' | 'area' | 'bar' | 'histogram' | 'pie' | 'donut' | 'radialBar' | 'scatter' | 'bubble' | 'heatmap' | 'candlestick' | 'radar';
    series: ApexAxisChartSeries | ApexNonAxisChartSeries;
    width?: string | number;
    height?: string | number;
    // method
  }

  namespace VueApexCharts {
    function install(app: typeof Vue): void;
  }

  export default VueApexCharts;
}

declare module 'vue/types/vue' {
  import ApexCharts from 'apexcharts';

  interface Vue {
    $apexcharts: typeof ApexCharts;
  }
}

```

Using TypeScript 3.3.3

**Comment by atilkan** [comment]
@divinespear Please create a PR.

**Comment by BnMcG** [comment]
@divinespear This could also possibly go into the DefinitelyTyped repo?

**Comment by atilkan** [comment]
@BnMcG DefinitelyTyped is deprecated.

**Comment by divinespear** [comment]
@atilkan I made PR. please check it.

**Comment by junedchhipa** [comment]
@divinespear Thanks, merged it. Will release on npm soon.

**Comment by atilkan** [comment]
@divinespear Thanks.

**Comment by mika76** [comment]
Is this available through https://github.com/DefinitelyTyped/DefinitelyTyped or how do I use it?

**Comment by divinespear** [comment]
@mika76 It will be released soon by @junedchhipa. If you don't have patience, you can install from this repository directly until release.

**Comment by mika76** [comment]
Oh I see it will just be available automatically when updating - so no need to download separate types... Perfect!

**Comment by junedchhipa** [comment]
Thanks for reminding. Just released 1.3.2 on npm with the typings included.

**Comment by mika76** [comment]
Just tried it but it's not working for me. I'm using vue cli 3, https://github.com/vuejs/vue-class-component and https://github.com/kaorun343/vue-property-decorator

As soon as I took the new version typescript started reporting weird errors with Vue itself 
eg: 
```
40:5 Argument of type '{ components: { Panel: typeof Panel; apexchart: typeof VueApexCharts; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
  Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to write 'component'?
    38 |
    39 | @Component({
  > 40 |     components: { Panel, apexchart: VueApexCharts },
       |     ^
    41 | })

```

**Comment by junedchhipa** [comment]
@divinespear Can you test it too? I just released without any modification.

**Comment by mika76** [comment]
@divinespear I'll give it a try sometime today and let you know - I can see if it's both it could be a problem - maybe splitting the types into different files would help? (I must admit the whole typescript definition file story is a bit confusing to me)

**Comment by divinespear** [comment]
@mika76 It may hard because original .js already exported both in same name...

**Comment by mika76** [comment]
Yeah it seems to work fine if imported as a global plugin, but does not work if you import as a local component. The thing is, without the types it works fine so just by adding in the types you might be causing confusion and issues for people. I'm sure there is a way to do it, but I'm not a typescript guru - anybody else know how to sort this out?

**Comment by divinespear** [comment]
@mika76 I've got short test on my company's project and got good news! :tada:
@junedchhipa Please check my new PR.
