### ISSUE TITLE
Update vue-apexcharts

### ISSUE THREAD

**Issue by Mishkoo93** [apexcharts/vue-apexcharts#334]
Hello, could you please update depencies for vue-apexcharts, for version 3.26.

Thank you.

**Comment by ricky11** [comment]
Yes, is it possible to find out what version of apexcharts vue-apexcharts is using?

**Comment by ordago** [comment]
@ricky11 

https://github.com/apexcharts/vue-apexcharts/blob/84a163b30b53ca1d1a396978b557509334dbdd23/package.json#L26
