### ISSUE TITLE
implement on nuxt js

### ISSUE THREAD

**Issue by chokies** [apexcharts/vue-apexcharts#34]
do you have a sample on how to implement on nuxt js?

**Comment by romain1304** [comment]
any news about implementing with Nuxt ....?
thanks

**Comment by romain1304** [comment]
@chokies Did you find a solution ? I see that you closed the discussion,
thanks!

**Comment by chokies** [comment]
@romain1304  yes

**Comment by junedchhipa** [comment]
@chokies Can you post the solution, please? What parts needed to be changed to make it work?

**Comment by chokies** [comment]
create a plugin

vue-apexchart.js

`import Vue from 'vue'
import VueApexCharts  from 'vue-apexcharts'

Vue.component('apexcharts', VueApexCharts)`

load the plugin and add it on the build on nuxt-config.js 

`{ src : '~/plugins/vue-apexchart.js', ssr : false },`

`/*
   ** Build configuration
   */
  build: {
    vendor : ['vue-apexchart'],
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {
      const vueLoader = config.module.rules.find(
        rule => rule.loader === "vue-loader"
      );
      vueLoader.options.transformToRequire = {
        img: "src",
        image: "xlink:href",
        "b-img": "src",
        "b-img-lazy": ["src", "blank-src"],
        "b-card": "img-src",
        "b-card-img": "img-src",
        "b-carousel-slide": "img-src",
        "b-embed": "src"
      };
    }
  }`

**Comment by san4io** [comment]
WARN  vendor has been deprecated due to webpack4 optimization

**Comment by connecteev** [comment]
@chokies this does not work in nuxt. ANy idea?
``` cannot read property 'document' of undefined```

**Comment by consuman** [comment]
@chokies 

I tried it three times now, I cant get it to work. Could you maybe share a bit more detailed how you maneged it to work? Would be much appreciated!!

**Comment by DiegoPerea** [comment]
1. Create a plugin:
//vue-apexchart.js
`import Vue from 'vue'
import VueApexCharts from 'vue-apexcharts'

Vue.component('apexcharts', VueApexCharts)
`

2. Add plugin in your nuxt.config.js
`  /*
   ** Plugins to load before mounting the App
   */
  plugins: [{ src: '~/plugins/vue-apexchart.js', mode: 'client' }],`

3. Create a component:
//chart.js
`<template>
  <div>
    <apexchart
      width="500"
      type="bar"
      :options="options"
      :series="series"
    ></apexchart>
  </div>
</template>
<script>
import apexchart from 'vue-apexcharts'
export default {
  components: {
    apexchart
  },
  data() {
    return {
      options: {
        chart: {
          id: 'vuechart-example'
        },
        xaxis: {
          categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
        }
      },
      series: [
        {
          name: 'series-1',
          data: [30, 40, 45, 50, 49, 60, 70, 91]
        }
      ]
    }
  }
}
</script>
`
This worked for me.

**Comment by consuman** [comment]
Nice, thank you very much! Got it working with two minor corrections:

In nuxt config I've put: { src: '~/plugins/vue-apexchart.js', ssr: false 
} and in my template, there was no need to import it again. It works as 
component out of the box as <apexcharts/> since we imported it before in 
the plugin and made it globally available.

The main difference to what I tried before, was importing it as a Vue 
Component in the Plugin. That solved it for me, thank you friend! Made 
my day!!
Nico

**Comment by ndan** [comment]
In case you don't want to import apexcharts under `~/plugins/vue-apexchart.js`:

```
<template>
  <client-only>
    <component
      :is="apexchart"
      height="160"
      width="320"
      type="area"
      :options="options"
      :series="series"
    />
  </client-only>
</template>

```
```javascript

<script>
export default {
  computed: {
    apexchart() {
      return () => {
        if (process.client) {
          return import('vue-apexcharts')
        }
      }
    }
  }
}
</script>
```

**Comment by thisromantelecom** [comment]
> @chokies this does not work in nuxt. ANy idea?
> ` cannot read property 'document' of undefined`

apex resolve promise,
use lazyload, like aka 
![image](https://user-images.githubusercontent.com/53601966/67390558-8e75bb00-f5a5-11e9-94d6-c3812cbecee2.png)

**Comment by waspinator** [comment]
```vue
<template>
  <client-only>
    <div>
      <VueApexCharts
        width="500"
        type="bar"
        :options="chartOptions"
        :series="series"
      ></VueApexCharts>
    </div>
  </client-only>
</template>

<script>
export default {
  components: {
    VueApexCharts: () => import('vue-apexcharts')
  },
  data() {
    return {
      chartOptions: {
        chart: {
          id: 'vuechart-example'
        },
        xaxis: {
          categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
        }
      },
      series: [
        {
          name: 'series-1',
          data: [30, 40, 35, 50, 49, 60, 70, 91]
        }
      ]
    }
  }
}
</script>
```

**Comment by tanvir510** [comment]
> { src: '~/plugins/vue-apexchart.js', ssr: false }

Could you please share your code? Actually, it does not work for me still now.

**Comment by sortidocorps** [comment]
For nuxtjs with Typescript

Install the package
`npm install vue-apexcharts --save`

Racine project vue-apexchart.d.ts
`declare module 'vue-apexcharts'`

Plugins folder add vue-apexchart.ts
`import Vue from 'vue'
import VueApexCharts from 'vue-apexcharts'

Vue.component('Apexchart', VueApexCharts)`

In nuxt.config.ts plugins tab
` { src: '~/plugins/vue-apexchart.ts', ssr: false },`

In my component vue
`<template>
  <client-only>
    <div>
      <Apexchart
        width="500"
        :type="type"
        :options="chartOptions"
        :series="series"
      ></Apexchart>
    </div>
  </client-only>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'nuxt-property-decorator'

@Component
export default class GenericChart extends Vue {
  @Prop({ required: true, default: 'bar' }) type!: string
  public chartOptions = {
    chart: {
      id: 'vuechart-example',
    },
    xaxis: {
      categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998],
    },
  }

  public series = [
    {
      name: 'series-1',
      data: [30, 40, 35, 50, 49, 60, 70, 91],
    },
  ]
}
</script>`

And it's works great :)

**Comment by avral** [comment]
@waspinator Thanks! But, you solution may cause memory leak when nuxt ssr is enabled. Just realised it after production server fails periodically.

@sortidocorps Solutions are works perfect 🙏🏻

**Comment by rajmohan6268** [comment]
> ```
> <template>
>   <client-only>
>     <div>
>       <VueApexCharts
>         width="500"
>         type="bar"
>         :options="chartOptions"
>         :series="series"
>       ></VueApexCharts>
>     </div>
>   </client-only>
> </template>
> 
> <script>
> export default {
>   components: {
>     VueApexCharts: () => import('vue-apexcharts')
>   },
>   data() {
>     return {
>       chartOptions: {
>         chart: {
>           id: 'vuechart-example'
>         },
>         xaxis: {
>           categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]
>         }
>       },
>       series: [
>         {
>           name: 'series-1',
>           data: [30, 40, 35, 50, 49, 60, 70, 91]
>         }
>       ]
>     }
>   }
> }
> </script>
> ```

this worked

**Comment by salsasteve** [comment]
Also worked for me 
`"nuxt": "^2.15.8",
    "nuxt-buefy": "^0.4.13",
    "vue": "^2.6.14",`

**Comment by zhouzilong2020** [comment]
Any idea on how to solve this in Nuxt3?

**Comment by kriordan37** [comment]
anyone get this to work in nuxt3? Ive tried the things could be i migrated to from the options api to the composition api incorrectly but i gave it a thrice over.

**Comment by Sandr0oo** [comment]
@kriordan37 Did you make it? I also can’t make him work in nuxt 3. Help, please.

**Comment by Sandr0oo** [comment]
It works.
```
<template>
  <div>
    <apexchart type="line" :options="chartOptions" :series="series"></apexchart>
  </div>
</template>

<script>
import VueApexCharts from "vue3-apexcharts";
export default {
  components: {
    apexchart: VueApexCharts,
  },
  data() {
    return {
      chartOptions: {
        chart: {
          background: "#fff",
          width: "100%",
          height: 50,
        },
        xaxis: {
          categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998],
        },
      },
      series: [
        {
          name: "series-1",
          data: [30, 40, 35, 50, 49, 60, 70, 91],
        },
      ],
    };
  },
};
</script>
```

**Comment by CiaranGames** [comment]
> It works. Vue 3. Nuxt 3.
> 
> ```
> <template>
>   <div>
>     <apexchart type="line" :options="chartOptions" :series="series"></apexchart>
>   </div>
> </template>
> 
> <script>
> import VueApexCharts from "vue3-apexcharts";
> export default {
>   components: {
>     apexchart: VueApexCharts,
>   },
>   data() {
>     return {
>       chartOptions: {
>         chart: {
>           background: "#fff",
>           width: "100%",
>           height: 50,
>         },
>         xaxis: {
>           categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998],
>         },
>       },
>       series: [
>         {
>           name: "series-1",
>           data: [30, 40, 35, 50, 49, 60, 70, 91],
>         },
>       ],
>     };
>   },
> };
> </script>
> ```

I tried this in Nuxt v3 and even wrapped the apexchart tag in ClientOnly but im still getting window is not defined, any help?

**Comment by danielvlla** [comment]
Can this issue be opened again? The above solutions do not work for me on Nuxt 3

**Comment by ayodejipy** [comment]
An updated solution to use in **Nuxt 3** is to add the `.client` suffix to your plugin name while you're registering apexcharts globally.

`apexChartPlugin.client.(js/ts)`

```
import VueApexCharts from "vue3-apexcharts";

export default defineNuxtPlugin((nuxtApp) => {
	nuxtApp.vueApp.use(VueApexCharts)
})
```

This would only execute on the client where it has access to the windows object.
