### ISSUE TITLE
donut chart now show percentage when value from 1% to 3%

### ISSUE THREAD

**Issue by rs-cuongph** [apexcharts/vue-apexcharts#349]
![image](https://user-images.githubusercontent.com/64763246/119234851-3379c080-bb5a-11eb-8df9-45d185769a62.png)
donut chart now show percentage when value from 1% to 3%.is it a bug ?
can anyone help me, pls.

**Comment by ordago** [comment]
It just means there is not enough space to show render the text. I think it's the expected behaviour.
