### ISSUE TITLE
Feature to change the look of the dashed line on tooltip

### ISSUE THREAD

**Issue by swogo-martins** [apexcharts/vue-apexcharts#358]
From what I understood according to the documentation there isn't an option to change how the line appears, it is always a static dashed grey line. I would like to configure it, using a static line with a specific color, how could I achieve that using the options object?

Here is an image of the dashed line I am talking about:

![apexchart_dashedline](https://user-images.githubusercontent.com/46926575/122977651-90e97300-d38d-11eb-925b-53d69d65d7f9.png)

Let me know if this is already possible, or it would require a feature request.
Thank you!

**Comment by christopherkindl** [comment]
+1

**Comment by alpercun** [comment]
@swogo-martins , did you find a solution to the problem?

**Comment by alpercun** [comment]
When you examine the chart, you can see that the dashed line has a class. You can change the display of this dashed line with `css`. The dashed line has a class called `apexcharts-xcrosshairs`.

For example;

```scss
.apexcharts-xcrosshairs {
   stroke-linecap: round;
   stroke-width: 4px;
   stroke-dasharray: 0;
   stroke: aqua;
}
```
You can find the output of the code [here](https://codesandbox.io/s/apx-line-basic-forked-p402y?file=/src/styles.css:124-236).
