### ISSUE TITLE
Annotations overlapping

### ISSUE THREAD

**Issue by amroessam** [apexcharts/vue-apexcharts#36]
Hi

The annotations feature in ApexCharts doesn't dynamically calculate padding.
Attached is a screenshot of the annotations overlapping

![image](https://user-images.githubusercontent.com/15579070/50261219-083c9580-0425-11e9-9e44-64dcb0c21821.png)

**Comment by junedchhipa** [comment]
Sorry for the delayed response.
May I get a codepen demo of how you achieved this?

**Comment by amroessam** [comment]
Sorry for being late, here's the [codepen](https://codepen.io/anon/pen/LMmOzN)

**Comment by junedchhipa** [comment]
That is the expected behavior.
If there is no space to put annotations, they will overlap on one another. I don't have an idea how to prevent the overlap in this case.

**Comment by amroessam** [comment]
Maybe the font size could be dynamic to fit the space?
Thanks for looking into it though

**Comment by junedchhipa** [comment]
You can try setting dynamic font-size based on text size as you are already adding annotations in a loop.

```javascript
annotations: {
  xaxis: {
   label: {
    style: {
      fontSize: text.length < 5 ? '10px' : '12px'
     } 
   }
  }
}
```
https://apexcharts.com/docs/options/annotations/#xlabelFontSize
