### ISSUE TITLE
Brush chart not working in Vue3

### ISSUE THREAD

**Issue by kalenpw** [apexcharts/vue-apexcharts#362]
I am using Vue3 with Vite and running into trouble getting a brush chart to work.

Gif of issue: as you can see the brush changing doesn't update the primary graph
![Peek 2021-07-07 20-18](https://user-images.githubusercontent.com/13550971/124851915-aa2f1980-df60-11eb-87a6-66b161f1954d.gif)

I installed Apex via: 
`npm install --save vue3-apexcharts` and `npm install --save apexcharts`

I updated my main.js to look like this:

```js
import { createApp } from 'vue'
import App from './App.vue'
import VueApexCharts from 'vue3-apexcharts'
import './index.css'

createApp(App).use(VueApexCharts).mount('#app')
```

I couldn't get Apex Charts working in a Code Sandbox, but here is a template which has all the requisite info (and doesn't work).

```vue
<template>
    <div id="wrapper">
        <div id="chart-line2">
            <apexchart
                type="line"
                height="230"
                :options="primaryOptions"
                :series="primarySeries"
            ></apexchart>
        </div>
        <div id="chart-line">
            <apexchart
                type="line"
                height="100"
                :options="mapOptions"
                :series="mapSeries"
            ></apexchart>
        </div>
    </div>
</template>
 
<script>
export default {
    name: "TestGraph",
    data: function () {
        let data = [
            [1327532400000, 135],
            [1327532400000, 155],
            [1327618800000, 135],
            [1327964400000, 155],
            [1328223600000, 165],
            [1328569200000, 150],
            [1328742000000, 180],
            [1330383600000, 145],
            [1330483600000, 145],
            [1330583600000, 145],
            [1330883600000, 145],
            [1331083600000, 145],
            [1331183600000, 145],
            [1331283600000, 145],
        ];

        return {
            primaryOptions: {
                chart: {
                    id: "chart2",
                    type: "line",
                    height: 230,
                    toolbar: {
                        autoSelected: "pan",
                        show: false,
                    },
                },
                colors: ["#546E7A"],

                dataLabels: {
                    enabled: false,
                },
                fill: {
                    opacity: 1,
                },

                xaxis: {
                    type: "datetime",
                    labels: {
                        datetimeFormatter: {
                            year: "yyyy-MM-dd",
                            month: "yyyy-MM-dd",
                            day: "yyyy-MM-dd",
                            hour: "yyyy-MM-dd",
                        },
                    },
                },
                title: {
                    text: "Dummy",
                    align: "center",
                },
            },
            // end primary options
            mapOptions: {
                chart: {
                    id: "chart1",
                    height: 130,
                    type: "area",
                    brush: {
                        target: "chart2",
                        enabled: true,
                    },
                    selection: {
                        enabled: true,
                        xaxis: {
                            min: new Date("24 Jan 2012").getTime(),
                            max: new Date("10 Mar 2012").getTime(),
                        },
                    },
                },
                colors: ["#008FFB"],

                xaxis: {
                    type: "datetime",
                    tooltip: {
                        enabled: false,
                    },
                },
                yaxis: {
                    tickAmount: 2,
                },
            },
            primarySeries: [
                {
                    data: data,
                },
            ],
            mapSeries: [
                {
                    data: data,
                },
            ],
        };
    },
};
</script>
```

**Comment by Quasarman** [comment]
@kalenpw Did you find any solution for this? I have the same issue.

**Comment by EmanueleCoppola** [comment]
@kalenpw 

I'm having the same issue here.
I've tried the fix explained [here](https://github.com/apexcharts/apexcharts.js/issues/2132) but it didn't work.
I'll see if I can dig deeper this issue in the next days.

I higly doubt that I will find something useful...

**Comment by Qualzz** [comment]
Arf, I was relying a lot on this brush feature but faced the same issue.

**Comment by kozel-aliaksei** [comment]
Does any one managed to fix it?

**Comment by GusMarroquin** [comment]
Does any one managed to fix it?

**Comment by placid2000** [comment]
Just came across the same. Too bad

**Comment by anderson-lactec** [comment]
Same problem too.

**Comment by SebastianRochert** [comment]
I also encountered the same problem.

**Comment by Qualzz** [comment]
At this point I believe this will never be fixed. I'm not saying that in a
negative way, I wish I had more experience in this library to help.

**Comment by TedCermitech** [comment]
Same problem...

**Comment by travis-mod-io** [comment]
Ran into this same problem but was able to create a workaround in the meantime by using `@selection` event from vue3-apexcharts and passing the xaxis min and max values from the selection through to the zoomX() function of the first chart.

e.g. 

`@selection="(brushChartContext, { xaxis }) => mainChartRef.zoomX(xaxis.min, xaxis.max)"`

**Comment by gentlekenny** [comment]
just commenting so it doesn't close. Please fix, this is really handy

**Comment by ivohutasoit** [comment]
+1

**Comment by Kylo6** [comment]
Still not working it seems.

**Comment by ryuchaehwa** [comment]
still nothing?

**Comment by Qualzz** [comment]
It's been several years now. I don't think it will ever be fixed.

**Comment by everypreciousday** [comment]
hope this is fixed

**Comment by aimanzaidan** [comment]
same problem here

**Comment by sh4nm** [comment]
+1

**Comment by nanjarapalli** [comment]
> Ran into this same problem but was able to create a workaround in the meantime by using `@selection` event from vue3-apexcharts and passing the xaxis min and max values from the selection through to the zoomX() function of the first chart.
> 
> e.g.
> 
> `@selection="(brushChartContext, { xaxis }) => mainChartRef.zoomX(xaxis.min, xaxis.max)"`

worked for me (Vue3 & Vuetify3)

**Comment by Qualzz** [comment]
That's a bummer.

**Comment by arthurwolf** [comment]
Still having this issue in 2025....

I'd expect "uses vue" and "uses brush" is not that small a group that this is a trivial matter...

**Comment by guyqsmith** [comment]
@travis-mod-io's comment got me to:

`const mainChartRef = ref(null)
const brushChartRef = ref(null)
`
...

`<VueApexCharts
  ref="mainChartRef"
  type="line"
  height="230"
  :options="mainChartOptions"
  :series="chartSeries"
/>

<VueApexCharts
  ref="brushChartRef"
  type="area"
  height="130"
  :options="brushChartOptions"
  :series="chartSeries"
  @selection="onBrushSelection"
/>`

and

`
function onBrushSelection(_: any, { xaxis }: any) {
  if (mainChartRef.value) {
    mainChartRef.value.zoomX(xaxis.min, xaxis.max)
  }
}
`

Which did the trick for me, after hours of thinking I had my setup wrong and then finding this issue.

Hope this helps someone else in the future.
