### ISSUE TITLE
CSS problems with vue-apexcharts

### ISSUE THREAD

**Issue by FoudreNoire26i** [apexcharts/vue-apexcharts#363]
Hi, I tried to use vue-apexcharts, my graph is displayed but a CSS in vue-apexcharts/example/App.vue add properties to "#app" (like max-width: 800px). I don't know how can I remove these CSS properties or made it "scoped" at the component.
Anyone has some idea ? 
<img width="1756" alt="Capture d’écran 2021-07-28 à 11 45 14" src="https://user-images.githubusercontent.com/63561849/127301436-993d3b44-d8e7-4e58-9153-b1482e81e8a3.png">

**Comment by chite** [comment]
Did you solve this problem? It is not clear how did you use the chart, maybe you can show more detail. Or you can try to  comment out your code which reference the chart, solving the problem step by step.

**Comment by FoudreNoire26i** [comment]
I don't solve yet the problem, I uninstalled the package. I installed your package via the command line (meteor npm install vue-apexcharts), and the problem is that a CSS in the package override my #app CSS. Then as you can see, my page has 800px of max-width.
