### ISSUE TITLE
Column Chart - Hide shadow when data on hover

### ISSUE THREAD

**Issue by cskusuma14** [apexcharts/vue-apexcharts#378]
Hi, how to hide that shadow ?

<img width="677" alt="Screen Shot 2021-09-20 at 08 44 50" src="https://user-images.githubusercontent.com/48611465/133950997-c4062277-a730-458d-9d91-377dfa23f910.png">
 
 Is that a known issue ? Any idea to fix it ? Thanks a lot !

**Comment by rmarmitt** [comment]
Hi @cskusuma14 

Try this:

```
states: {
  hover: {
    filter: {
      type: 'none'
     }
  }
}
```

**Comment by mansimodi2019** [comment]
not working

**Comment by Patryqss** [comment]
The above answer doesn't work, so for anyone struggling with it, this is the solution:
```
xaxis: {
  crosshairs: {
    show: false
  }
}
```
