### ISSUE TITLE
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by odhikari** [apexcharts/vue-apexcharts#38]
Hello Team, 

I have to implement Heatmap chart in laravel vue js , but I got an error (
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not callable) .

 which is working fine in https://codesandbox.io/s/42yryo2957 link. 

Thanks,

**Comment by odhikari** [comment]
Actually, I'm implementing it in my local system. It's creating an issue because of vuejs but I don't know why it is happening.
When ever I disable one of the below js file  it works but I can't disable these files .

{!! Html::script(mix('js/manifest.js')) !!}
{!! Html::script(mix('js/vendor.js')) !!}
{!! Html::script(mix('js/app.js')) !!}

I need to run above js as well as 
{!! Html::script('//cdn.jsdelivr.net/npm/apexcharts') !!}

From vue I am not able to solve issue so I'm using with normal jquery.
Here is the code
<div id='heatmap'></div>
<script>
        $(document).ready(function() {

            function generateData(count, yrange) {
                       var i = 0;
                       var series = [];
                       while (i < count) {
                           var x = 'w' + (i + 1).toString();
                           var y = Math.floor(Math.random() * (yrange.max - yrange.min + 1)) + yrange.min;

                           series.push({
                               x: x,
                               y: y
                           });
                           i++;
                       }
                       return series;
                   }


                   var options = {
                       chart: {
                           height: 350,
                           type: 'heatmap',
                       },
                       dataLabels: {
                           enabled: false
                       },
                       colors: ["#008FFB"],
                       series: [{
                               name: 'Metric1',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric2',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric3',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric4',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric5',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric6',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric7',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric8',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           },
                           {
                               name: 'Metric9',
                               data: generateData(18, {
                                   min: 0,
                                   max: 90
                               })
                           }
                       ],
                       title: {
                           text: 'HeatMap Chart (Single color)'
                       },

                   }

                   var chart = new ApexCharts(
                       document.querySelector("#heatmap"),
                       options
                   );

                   chart.render();
        });
    </script>

**Comment by nolros** [comment]
For what is worth. I recently debugged some Laravel code and ran into a similar issue. It seems that the developer created a global namespace <code>Event</code> class which creates a conflict. 

Original code in app.js:

```
	import Event from './services/EventsService'
	window.Event = new Event();
```

Refactored to the following solved the problem:

```
	import Event from './services/EventsService'
	window.$eventService = new Event(); 
```

**Comment by yoyTeam** [comment]
> For what is worth. I recently debugged some Laravel code and ran into a similar issue. It seems that the developer created a global namespace `Event` class which creates a conflict.
> 
> Original code in app.js:
> 
> ```
> 	import Event from './services/EventsService'
> 	window.Event = new Event();
> ```
> 
> Refactored to the following solved the problem:
> 
> ```
> 	import Event from './services/EventsService'
> 	window.$eventService = new Event(); 
> ```

It's Work fine thanks!

**Comment by yeremiapinggi** [comment]
![Screen Shot 2019-11-05 at 04 06 47](https://user-images.githubusercontent.com/5475769/68158199-bab81100-ff81-11e9-8de9-0853564a3371.png)

need help please,
i just install on vuejs and got error like this

**Comment by dorogoff** [comment]
> For what is worth. I recently debugged some Laravel code and ran into a similar issue. It seems that the developer created a global namespace `Event` class which creates a conflict.
> 
> Original code in app.js:
> 
> ```
> 	import Event from './services/EventsService'
> 	window.Event = new Event();
> ```
> 
> Refactored to the following solved the problem:
> 
> ```
> 	import Event from './services/EventsService'
> 	window.$eventService = new Event(); 
> ```

It works for me too, thanks!
