### ISSUE TITLE
ResetZoom hide my graphic

### ISSUE THREAD

**Issue by BenDuh** [apexcharts/vue-apexcharts#380]
Hi, 

I'm using vue3-apexcharts with 1.4.1 version. I experimented a strange bug, when i click on reset zoom, xAxis and my differents graphics disappear. Do you know why ? 

<img width="600" alt="Capture d’écran 2021-09-24 à 16 56 27" src="https://user-images.githubusercontent.com/46995140/134696205-a9858882-ff35-4cdf-b5cc-1d61f2d210bf.png">
<img width="600" alt="Capture d’écran 2021-09-24 à 16 56 32" src="https://user-images.githubusercontent.com/46995140/134696212-dbe32de1-df9f-41cd-b2e9-da34b34ebb20.png">

**Comment by rmarmitt** [comment]
Hi @BenDuh 

I think this issue is related to [vue-apexcharts](https://github.com/apexcharts/vue3-apexcharts) repo.

Please, open an issue in these repo
