### ISSUE TITLE
Calling svgUrl method

### ISSUE THREAD

**Issue by isy** [apexcharts/vue-apexcharts#39]
Hi

I have tried the following.

```javascript
this.$refs.demoChart.chart.svgUrl();
```

- return
```
blob:http://localhost:4000/5c67f400-7bf3-4ee6-9f99-b3ca41677d91
```
Is this something wrong?

**Comment by junedchhipa** [comment]
Url looks like there is something wrong with the generation of SVG blob.
I will take a look soon.

**Comment by junedchhipa** [comment]
Replaced the `svgUrl()` with a new method `dataURI()` which returns correct base64 image dataURI.
Docs: https://apexcharts.com/docs/methods/#dataURI

**Comment by AbrahamBrookes** [comment]
Does this mean there is no way to extract an SVG anymore? Only a raster image?
