### ISSUE TITLE
vue apeccharts throws an error when using a computed height property

### ISSUE THREAD

**Issue by MBurchard** [apexcharts/vue-apexcharts#393]
I want a vue apexchart having a fix height of 300 if a parent elements width is greater then 480. If not it should have an auto height.

I'm using Vue 3.2 composition API.

```vue
<template>
  <div ref="localContainer" class="row chart border rounded">
    <div class="col-12">
      <apexchart :height="chartHeight" :options="options" :series="data" type="line"/>
    </div>
  </div>
</template>
```
The Typescript code only shows the relevant parts.
```ts
export default defineComponent({
  name: 'VrkVisitorChart',
  setup() {
    const localContainer = ref(null)

    const chartHeight = computed(() => {
      const div = localContainer.value ? localContainer.value as HTMLElement : null
      if (div && div.offsetWidth > 480) {
        console.debug('return height 300')
        return 300
      }
      console.debug('return height auto')
      return 'auto'
    })

    return {
      localContainer,
      data,
      options,
      chartHeight,
    }
  },
})
```
![grafik](https://user-images.githubusercontent.com/4256302/142458987-226ced23-317a-420b-a288-a3bef5edc048.png)

Setting height to 300 hard coded works. Auto works also. Only when using the computed the error is thrown,

**Comment by MinSomai** [comment]
I usually apply computed height to the parent and apexchart is set to `height="100%"`.

**Comment by kriordan37** [comment]
i got the same issue @MinSomai  do you have an example?
