### ISSUE TITLE
Uncaught (in promise) TypeError: ResizeObserver is not a constructor

### ISSUE THREAD

**Issue by iandrosov** [apexcharts/vue-apexcharts#398]
Hello, I am facing this error while loading chart inside Lightning Web Component LWC in Salesforce. I did not see any examples for this not sure if this can be done or may be I need to load some other JS dependencies such as 'resize-observer-polyfill'?

I built my example chart and it works in HTML page in Chrome browser. And usually such sample can work inside LWCs but not this one.

**Comment by cocktailjbonet** [comment]
I'm facing the same issue. Had you found a solution? In a developer org is working properly but in client sandbox no...
