### ISSUE TITLE
When changing `theme` in the `options` property of `apexchart`, the chart doesn't render till I refresh the page.

### ISSUE THREAD

**Issue by ciaransweet** [apexcharts/vue-apexcharts#400]
I'm using Vue3 and I have an `apexchart` like so:

```html
<template>
  <div>
      <apexchart height="350" :options="options" :series="series"></apexchart>
  </div>
</template>
```

We have a button on a page which uses the above component, which allows the user to change their theme between `light/dark`.

When this changes, the computed value I have in `options` also changes, which I would then expect to see represented by the chart re-rendering with the new theme.

Except, when I change the theme, from say `dark` to `light`, I get this:

![image](https://user-images.githubusercontent.com/9111975/149354921-017873b2-a378-42f8-9e33-0a963fc75ccb.png)

It seems like the reactiveness of the component to options changing isn't quite reliable. If I soft refresh the page, it then looks fine:

![image](https://user-images.githubusercontent.com/9111975/149355057-9dfc6c12-a203-4487-b98a-16383433813e.png)

**Comment by markchristianlacap** [comment]
you might need to add :key="isDark" to re render the component.

**Comment by ciaranevans** [comment]
@mperrien just an FYI!
