### ISSUE TITLE
Multi axis line chart yaxis negative bug

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/vue-apexcharts#41]
If you dynamically add data with negative axis (like from -200 to 200) and don't put them first in the order of the axis, the lines draw like the 0 is at the bottom. It works well if the axis are sorted by axis_min. I can't provide a codepen as of now but will add it later. 

First axis and data is a 0 to positive axis  : 
![image](https://user-images.githubusercontent.com/17592744/50979018-edc27d00-14f5-11e9-96da-3a71fe10e276.png)

With axis and data sorted by axis min :
![image](https://user-images.githubusercontent.com/17592744/50978930-b9e75780-14f5-11e9-83d3-e03780353619.png)

I suppose this is a minor forget somewhere but I'm willing to build up a codepen if needed.

**Comment by junedchhipa** [comment]
Good to see you again @arkhenstone  😁 
I would appreciate a codepen demo to quickly fix the bug.

**Comment by arkhenstone** [comment]
Finally had the time to make it : https://codepen.io/arkhenstone/pen/yGRKwP
