### ISSUE TITLE
Formatter of donut labels

### ISSUE THREAD

**Issue by ARM128bit** [apexcharts/vue-apexcharts#411]
Good day!
When I am trying to split a name of a donut label by a space like on a screenshot below
![image](https://user-images.githubusercontent.com/50628474/154502096-25e39a0c-36b8-4ade-8689-95928a4ffef6.png)
I get a successful label of donut, line breaks works fine
![image](https://user-images.githubusercontent.com/50628474/154502531-7d363ba8-3bcf-4046-9da8-9f55b33faf01.png)
But when I focus or click to another part of a donut I get a comma between words something like below:
![image](https://user-images.githubusercontent.com/50628474/154502906-6bc03b36-bfb5-4e90-821c-c9399b6a0340.png)

As a result, line breaks works fine at the first mount.

Best regards, Yuri

**Comment by itsboo07** [comment]
hey, could you help me get the entity value as lables value?
something like this?
`pie:
      donut:
        labels:
          show: true
          total:
            show: true
            label: Total
            formatter: |
              EVAL:function(w) {
                return {{states('sensor.processor_use')}} 
                }`
 for example in this they have made number of entities to show in center label value  but dont know how to add this in code to get the same result      
![image](https://user-images.githubusercontent.com/87331871/190877314-62d3a0d2-40b4-4d34-9353-43c16eb63acb.png)

**Comment by ARM128bit** [comment]
> hey, could you help me get the entity value as lables value? something like this? for example in this they have made number of entities to show in center label value but dont know how to add this in code to get the same result ![image](https://user-images.githubusercontent.com/87331871/190877314-62d3a0d2-40b4-4d34-9353-43c16eb63acb.png)
> 
> ```
>       donut:
>         labels:
>           show: true
>           total:
>             show: true
>             label: Total
>             formatter: |
>               EVAL:function(w) {
>                 return {{states('sensor.processor_use')}} 
>                 }
> ```


Hi, You can see below an example formatter function where is going calculation of values
![image](https://user-images.githubusercontent.com/50628474/197945867-4d188eb9-85ca-4859-b98e-8faec8be3515.png)

`formatter: function(w) {
  const total = w.globals.seriesTotals.reduce((a, b) => {
    return a + b;
  }, 0);
  return parseFloat(total).toLocaleString();
},`

**Comment by tmcdos** [comment]
I have the same issue as @ARM128bit - can someone help ?
