### ISSUE TITLE
Vue.js chart tooltip for downloading is visible but does not open

### ISSUE THREAD

**Issue by PrimozRome** [apexcharts/vue-apexcharts#42]
I am integrating Apexcharts into Vue/Nuxt application. Tooltip for downloading chart as PNG does not open. Any idea what could be wrong?

<img width="1765" alt="screenshot 2019-01-11 at 10 48 01" src="https://user-images.githubusercontent.com/1180467/51026300-78ef5180-158e-11e9-9dc2-1a973ee8c18d.png">

**Comment by junedchhipa** [comment]
Also, which version of ApexCharts are you using?

**Comment by PrimozRome** [comment]
@junedchhipa apexcharts 2.6.0 and vue-apexcharts 1.2.8

**Comment by PrimozRome** [comment]
Also is there a chance to add top margin to a chart so that those buttons are note so squeezed?

**Comment by junedchhipa** [comment]
You can position the toolbar using CSS as toolbar is drawn using HTML elements and resides outside SVG area.

```css
.apexcharts-toolbar {
  top: 10px;
}
```

**Comment by junedchhipa** [comment]
Were you able to solve it? I cannot reproduce it on my side. Maybe I would see a codepen/codesandbox demo to actually see what's happening.

**Comment by PrimozRome** [comment]
@junedchhipa no unfortunately not. Still have the same issue. 

I import ApexCharts and apexcharts-vue into nuxt-js project (larger SPA project). Very hard to reproduce same thing on the Codpen.

But my Apexchart code is very simple, let me post it here:

**Template**
```
<template>
    <!-- CHART -->
    <div class="row">
      <div class="col-sm-12">
        <h4>{{ $t('PRODUCTS.LAST_PRICE_HISTORY') }}</h4>
        <vue-apex-charts
          :options="options"
          :series="series"
          type="area"
          height="500"
          class="chart"
        />
      </div>
    </div>
</template>
```

**Script**

```
<script>
import VueApexCharts from 'vue-apexcharts'

export default {
  components: {
    VueApexCharts
  },

  data () {
    return {
      options: {
        chart: {
          id: 'Product-chart',
          toolbar: {
            show: true,
            tools: {
              download: true,
              selection: true,
              zoom: true,
              zoomin: true,
              zoomout: true,
              pan: true,
              reset: true
            },
            autoSelected: 'zoom'
          }
        },
        xaxis: {
          type: 'datetime'
        },
        yaxis: {
          labels: {
            formatter: function(val, index) {
              return val.toFixed(2)
            }
          }
        },
        dataLabels: {
          formatter: function(val, index) {
            return val.toFixed(2)
          }
        },
        tooltip: {
          y: {
            formatter: function(val, index) {
              return val.toFixed(2) + ' EUR'
            }
          }
        }
      },
      series: [
        {
          name: 'Production price',
          data: []
        },
        {
          name: 'Production price 2',
          data: []
        }
      ]
    }
  },

  mounted () {
    this.loading = true
    this.$axios.get('/products/' + this.rowData.id, {
      params: {
        include: 'lots'
      }
    }).then(response => {
      let data = response.data
      this.loading = false
      if(data.lots.length > 0) {
        this.createLotChart(data.lots)
      }
    })
  },

  methods: {
    createLotChart (lots) {
      let series = []
      let max = 0
      for (let lot of lots) {
        series.push({
          x: lot.created_at,
          y: parseFloat(lot.amount)
        })
      }
      this.series[0].data = series
    }
  }
}
</script>

```

Not sure how to approach to the problem to find out why dropdown is not showing :/. Any idea?

**Comment by junedchhipa** [comment]
You may try attaching click event on `.apexcharts-menu-icon` element, and then toggling the display of the menu.

```javascript
const elMenuIcon = document.querySelector('.apexcharts-menu-icon')
const elMenu = document.querySelector('.apexcharts-menu')

elMenuIcon.addEventListener('click', function() {
   if (elMenu.classList.contains('open')) {
      elMenu.classList.remove('open')
    } else {
      elMenu.classList.add('open')
    }
})
```

**Comment by PrimozRome** [comment]
@junedchhipa tried this and this works, but its kind of messy workaround to a very clean code :). Anyway good charting library so far. Tried few of them for Vue project and this one seems best ratio between functionality and easy-of-use.

**Comment by junedchhipa** [comment]
I agree it's a messy workaround. But, I am unable to produce this on my side, hence don't know the exact cause of the issue.

Thanks for the kind words :)

**Comment by PrimozRome** [comment]
@junedchhipa yeah I understand. Let me see if I can somehow find the cause of this, but since my code is more or less copy paste from the Getting started guide, I don't know. Must be something connected to my Nuxt.js/Vue.js environment.
