### ISSUE TITLE
Nuxt / vue-apexcharts in static mode

### ISSUE THREAD

**Issue by npltr62** [apexcharts/vue-apexcharts#421]
Is there a way to display charts when i generated static files in Nuxt?
i have blank page ...
 apex.js
`import Vue from 'vue'
import ApexChart from 'vue-apexcharts'

Vue.component('Apexchart', ApexChart)
`
nuxt-config
`  plugins: [
    { src: '~/plugins/apex.js', ssr: false }
  ],`

**Comment by rmarmitt** [comment]
@npltr62 https://github.com/apexcharts/vue-apexcharts/issues/34#issuecomment-544191308

**Comment by npltr62** [comment]
@rmarmitt yes but when i switched ssr in true , I had the same issue and error "Windows undefined"
it seems apexcharts doesn't render on server side

**Comment by rmarmitt** [comment]
Can you provide the .vue file of apexchart section?

Have you added <client-only> as wrapper?

**Comment by karis** [comment]
try this first [https://github.com/apexcharts/vue-apexcharts/issues/34#issuecomment-1496371580](nuxt config)
i hope this closed your issue
