### ISSUE TITLE
Apex-Charts reactive with Vue ?

### ISSUE THREAD

**Issue by UpsylonDev** [apexcharts/vue-apexcharts#424]
Apex-Charts data not responsive with view?
the options change but not the data on an onBeforeMount ???
are there examples with a simple change of data?

**Comment by Flatroy** [comment]
@UpsylonDev Hi, you have to update it this way from readme: https://github.com/apexcharts/vue-apexcharts#how-do-i-update-the-chart

**Comment by UpsylonDev** [comment]
thanks but this example does not work on data(series) . a lot of inconsistencies and contradictions in the documentation in this library which is really good.
I found that
     updateSeriesLine() {
            this.$refs.realtimeChart.updateSeries([{
                data: this.series[0].data,
            }], false, true);
        },
