### ISSUE TITLE
dataURI() method missing

### ISSUE THREAD

**Issue by alexkleinwaechter** [apexcharts/vue-apexcharts#43]
Hi there,
thanks for the great work on the dataURI issue. My jsPDF works perfect now. 
In order to make it work with your vue wrapper I had to add the method in your vue-apexcharts.js:
methods: { ......
,
      dataURI: function dataURI() {
        return this.chart.dataURI();
      }	

You should insert it and release it :-)

Best!
Alex

**Comment by junedchhipa** [comment]
Ah! right. Thanks for the catch, I will add that.
