### ISSUE TITLE
Remove Unnecessary Spacing in Charts

### ISSUE THREAD

**Issue by jsinhSolanki** [apexcharts/vue-apexcharts#44]
Hey, I am using apexchart in my project and I want to create a card which have full width charts.
So, I dont need any labels, legend etc. But even if I remove everything still I have some space around chart. Which I dont want. I want to cover that card/div with only chart(No Spaces).

Problem Demo:
[JSFiddle](http://jsfiddle.net/jsinh0001/8ekw7hsq/)

What I Want:
![charts](https://user-images.githubusercontent.com/31243533/51459496-d3529400-1d7e-11e9-854d-345fcc02a413.PNG)

**Comment by junedchhipa** [comment]
You can try removing left/right padding by

```javascript
grid: {
  padding: {
   left: 0,
   right: 0
  }
}
```

A full example of your updated [jsfiddle](http://jsfiddle.net/phe7s4Lg/)

**Comment by jsinhSolanki** [comment]
Thanks @junedchhipa.
