### ISSUE TITLE
Incorrect default XAxis title position

### ISSUE THREAD

**Issue by TadasMil** [apexcharts/vue-apexcharts#451]
Hey, by default `xaxis.title` is positioned on top of the chart area. Do this behaves as expected?
![image](https://user-images.githubusercontent.com/64957606/201661130-a140720a-f10a-4975-bed5-4dda895ea85d.png)

I'm attaching reproducible example [https://codepen.io/tadasmil/pen/gOGwPwM](url)

**Comment by QuentinLavieville** [comment]
Hello, i have the same problem. I had to put another div under the graph to put the title, but its not something i can keep in my app

**Comment by TadasMil** [comment]
With the version of apexcharts:3.37.0, this should be fixed.
