### ISSUE TITLE
toggleDataSeries onItemClick in pie chart legend not work

### ISSUE THREAD

**Issue by nonomaxxis** [apexcharts/vue-apexcharts#455]
hi ,
```
legend: {
  onItemClick: {
    toggleDataSeries: true,
  },
},
```

in pie chart not work. when click on legend just highlight and visibility  not work.

**Comment by oicaroalmeida** [comment]
No one see this issue?

**Comment by mcsantos7** [comment]
Same in (https://github.com/apexcharts/apexcharts.js/issues/257)
