### ISSUE TITLE
Tooltip is not working in some charts

### ISSUE THREAD

**Issue by jsinhSolanki** [apexcharts/vue-apexcharts#48]
Hey, recently I updated vue-apexcharts to latest release since then my tooltip in some of my charts is not working.

They includes:
Pie chart
donut chart
radial etc.

I can not figure out whats problem. I have similar [jsfiddle](http://jsfiddle.net/jsinh0001/8ekw7hsq/) to yours as you provided in demo.
Still tooltip is not working.

And one more thing,
this pie charts, donut charts and radial chart have some space below them.
You can also see this problem in jsfiddle.

Thanks.

**Comment by junedchhipa** [comment]
Regarding the extra spacing, the height is auto-calculated based on width for donuts/radial.

If the spacing messes up your normal layout, I suggest giving a fixed height instead of `auto`
```javascript
chart: {
   width: '100%',
   height: 300
}
```
