### ISSUE TITLE
Sort the yaxis label in asc order

### ISSUE THREAD

**Issue by karenwanga** [apexcharts/vue-apexcharts#491]
Hi Sir,

My chart type is rangeBar, how can I sort the yaxis in asc order?

![image](https://github.com/apexcharts/vue-apexcharts/assets/37425098/33aaba5d-b915-45ff-97db-a16fa8d05bc6)

Thank you.

**Comment by junedchhipa** [comment]
You have to manually sort the x property of `series.data` array when building it.
