### ISSUE TITLE
Flickering chart when updating data

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/vue-apexcharts#5]
I suppose this comes from the vue-wrapper since it works like a charm on the demo site. When I replace my series data in vue, the transitionning works but the chart is flickering just before.

See below : 
![issue_flickr_vue](https://user-images.githubusercontent.com/17592744/45140652-cbb99680-b1b3-11e8-88b7-e3d339f02271.gif)

**Comment by arkhenstone** [comment]
I'm closing this since it does not belong there.

**Comment by junedchhipa** [comment]
This commit https://github.com/apexcharts/apexcharts.js/commit/1ded7a0fd46d039eb7d1fff1dffda6a3ec91150f fixes the flickering

**Comment by skegel13** [comment]
I am still seeing this occur on the latest versions of Apex Charts and Vue. We are using async functions to fetch the data from the server, then computed properties to format the data, and those properties are used for the series.

**Comment by mehdibahrami** [comment]
@junedchhipa Cloud you please check this one?
![Apex](https://user-images.githubusercontent.com/63710663/125204574-3b6cfb80-e293-11eb-9a0f-64eb40b040a0.gif)
I checked the data from WebSocket and it doesn't have a problem.
I'm using apex and vue3-apexcharts and my config is:
```
export const speedGaugeChartOptions = {
 plotOptions: {
    radialBar: {
      startAngle: -90,
      endAngle: 90,
      hollow: {
        size: "65%",
      },
      track: {
        show: true,
        strokeWidth: "20%",
      },
      dataLabels: {
        name: {
          offsetY: 25,
          color: "#6b7280",
          show: true,
        },
        value: {
          offsetY: -10,
          color: "#8a63a3",
          fontSize: "2rem",
          formatter(val) {
            return `${parseFloat(val)}`;
          },
        },
      },
    },
  },
  chart: {
    sparkline: {
      enabled: true,
    },
  },
  fill: {
    colors: [
      function ({ value }) {
        if (value <= SPEED_LIMIT) {
          return "#7ca363";
        } else {
          return "#AD6D6D";
        }
      },
    ],
    type: "solid",
  },
  labels: ["km/h"],
};
```

**Comment by BalajiM1603** [comment]
The solution for chart flickers is you need to use render function only page loading. when you want to update the chart data you need to use the methods in apex chart.

ApexCharts.exec('mychart', 'updateSeries', [{
  data: [32, 44, 31, 41, 22]
}], true);
