### ISSUE TITLE
Can't call vue methods inside chart event functions

### ISSUE THREAD

**Issue by gusMoreno** [apexcharts/vue-apexcharts#51]
Hi, I have a dashboard, where I update some charts whenever the main chart is clicked. 
I was able to update the charts with a button click, although, I am not able to do it when clicking a slice of the main pie chart.

Clicking a slice of the pie, throws the following error:

<img width="507" alt="captura de tela 2019-01-30 as 16 21 11" src="https://user-images.githubusercontent.com/6085835/52003261-288f5380-24ab-11e9-8e83-c5e59005ffda.png">

As per documentation, this is the code I use to receive the event:

```javascript
            pieChartOptions1: {
                chart: {
                    events: {
                      dataPointSelection(event, chartContext, config) {
                        this.showPerDisciplineName(config.dataPointIndex)
                      },
                  } 
                },
                ...
            }
```

Also, I have the method `showPerDisciplineName` declared in the methods section, and I can even access it from button clicks, so it shouldn't throw that error.

```javascript
methods: {
  ...
  showPerDisciplineName(seriesIndex){
    ...
  }
}
```
I read all the documentation, so I believe the issue is not on my side.

Is there a way to access the Vue methods from the chart events?

Thanks!

**Comment by junedchhipa** [comment]
You have to call Vue methods from an arrow function, as `this` is currently pointing to the chart instance and not the Vue instance.

I have provided a complete example of calling Vue method from inside `dataPointSelection` method in a codepen - https://codepen.io/apexcharts/pen/VgPamb

You will have to move the `chartOptions` to a computed property and convert the function declaration to an ES6 arrow function as shown in the example. In the example, click on the bars and see how it calls the method defined in the Vue instance from ApexCharts event.

**Comment by gusMoreno** [comment]
Thank you very much @junedchhipa !! It worked!
By the way, excellent work with the charts! It is a great fit to my project!
