### ISSUE TITLE
[BUG] - Use CSS color variables in the chart config not reflect to PNG, SVG, and dataURI of the chart

### ISSUE THREAD

**Issue by eng-ahmad-sameer** [apexcharts/vue-apexcharts#521]
If the user uses a CSS variable as a color for the chart like the one below:
```
 colors: ["var(--theme-color)", "#000"],
```
It reflects the chart correctly, but the saved SVG or PNG and the chart data do not reflect the specified color.
The saved PNG will be like this:
![d8liskvt](https://github.com/user-attachments/assets/96f5aaa4-b0ab-4f6a-bf3e-6467c1a9ea33)

The expected PNG:
![grsgvg6r](https://github.com/user-attachments/assets/46fd6b4c-7426-4574-8549-c540a68e0b34)

The same applied to SVG and chart data URI

**Comment by chaduhwan** [comment]
I've been through the same problem.

```
.apex Chart-y-axis-small text {
Conversion: Rotation (0 degree);
}
```
CSS is not reflected in png, svg.
Only the initial screen (decorated with built-in options) is downloaded.
