### ISSUE TITLE
Example for more than one Chart

### ISSUE THREAD

**Issue by andreas83** [apexcharts/vue-apexcharts#55]
I'm spend now hours trying to figure out how to display more than one chart inside one vue component.
 
`            <apexchart v-for="(item, index) in sensor_item_list"   width="500" :id="index" type="area" :options="item.options" :series="item.seriesdata"></apexchart>
`
Usually i end up seeing all charts with same seriesdata. 

```
async getDashboardItems(dashboard_id) {

    let currentObj = this;
    const res = await axios.get('/api/dashboard/' + dashboard_id + '/items/', {});

    var i;
    for (i = 0; i < res.data.length; i++) {

        let response = await axios.get('/api/sensors/' + sensor_id + '/data', {});
        var series = response.data.map(function (item)
        {

            let t = item.created_at.split(/[- :]/);
            var d = new Date(Date.UTC(t[0], t[1] - 1, t[2], t[3], t[4], t[5]));

            return [d, item.value];

        });
        currentObj.sensor_item_list[i].seriesdata[0].data = series;

    }

}
```

Would be more than happy if you could provide a example.

**Comment by junedchhipa** [comment]
I see that you're updating the series variable like this
```javascript
currentObj.sensor_item_list[i].seriesdata[0].data = series;
```

Instead, you should try updating the whole `seriesData` prop
```javascript
currentObj.sensor_item_list[i].seriesdata = [{
  data: series
}];
```

**Comment by FoxBearBear** [comment]
> Maybe the issue is related to Vue and not directly ApexCharts.
> I have already provided an example of multiple charts in vue-demos as seen here - https://apexcharts.com/vue-chart-demos/line-charts/syncing-charts/
> 
> Can you create a codesandbox demo of the issue? Use this template - https://codesandbox.io/s/pwwz8009n0

And what about if one does not now how many charts will be drawn at a time?
