### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by darkoromanov** [apexcharts/vue-apexcharts#57]
Maybe we should update package.json requiring the last stable version of apexcharts? I had to manually include the https://cdn.jsdelivr.net/npm/apexcharts@latest script because the scatter chart is buggy, using the latest version if works correctly.

**Comment by junedchhipa** [comment]
The core apexcharts is a peer dependency of `vue-apexcharts`, so you have to manually install the peer dependency when you install `vue-apexcharts`.

Anyways, I will update the version whenever the core library is updated if installing peer dependency installs the version specified in package.json.
