### ISSUE TITLE
Auto resize charts if parent div's width is changed

### ISSUE THREAD

**Issue by jsinhSolanki** [apexcharts/vue-apexcharts#58]
Hi, in my app I have div as card and it's width is changed when user clicks on button.
Now problem is when card(div) width is changed chart is not resizing.

This is serious problem for me. Can u plz help me.
You can check this in [jsfiddle](https://jsfiddle.net/jsinh0001/vknmjqp3/)

**Comment by junedchhipa** [comment]
Just fixed it. 
Patch will be released soon.
