### ISSUE TITLE
Stacked total in tooltip

### ISSUE THREAD

**Issue by ivarsmednis** [apexcharts/vue-apexcharts#59]
Hi!
Is it possible to have total in stacked chart tooltip? For example i have stacked area with two series - Red apples and Green apples. I would like to show information about total apples, maybe in tooltip (like in Amazon AWS cost explorer).

Currently i have 3 series (Red apples, Green apples, Total apples) with non-stacked area chart, but it doesn't look as good as stacked chart.

**Comment by junedchhipa** [comment]
With some minor tweaks, this is achievable easily.
```javascript
     tooltip: {
        custom: function({series, seriesIndex, dataPointIndex, w}) {
          return `
            <div class="apexcharts-tooltip-custom">
              <strong>Total:</strong> ${w.globals.stackedSeriesTotals[dataPointIndex]}
            </div>`
        }
      }
```

```css
.apexcharts-tooltip-custom {
      padding: 10px;
}
```

[Codepen Example](https://codepen.io/apexcharts/pen/OdoGRa)

**Comment by ivarsmednis** [comment]
Thank you for prompt reply, powerful stuff!
