### ISSUE TITLE
Pie not displaying if labels from list

### ISSUE THREAD

**Issue by alc32** [apexcharts/vue-apexcharts#6]
If labels: ['a', 'b', 'c', 'd'], pie is rendered, but if labels: this.labels1 is not rendered.

[Codepen](https://codepen.io/alc32/pen/QVpErx)

**Comment by junedchhipa** [comment]
You should use computed properties for such a use case.
Here is the updated [codepen](https://codepen.io/apexcharts/pen/NLydjO) 

https://vuejs.org/v2/guide/computed.html
