### ISSUE TITLE
Combined series tooltip

### ISSUE THREAD

**Issue by goalstogrowth** [apexcharts/vue-apexcharts#60]
I'll start by saying this is the best charting library I've seen. It's intuitive and it just works they way you would expect and want.

Now to the question. I have a multi-series line chart with an a-axis of date. The problem I noticed is that the series behind another won't popup if they share a date. In the screen capture I'm including the orange series point won't show even if you hover over the point, instead the green series shows. I'd like to have a tooltip that lists all the points for a date. I like the format of the default tooltip with the heading and series color, but need a little help with the loop to print out each if a value is present.
![capture](https://user-images.githubusercontent.com/44439918/52893308-0105df80-3169-11e9-98b3-aedc5dba8123.PNG)

**Comment by junedchhipa** [comment]
Can you please create a codepen demo with the same series and configuration?

**Comment by junedchhipa** [comment]
The demo doesn’t have to be in vue.js necessarily.

**Comment by goalstogrowth** [comment]
https://codesandbox.io/s/40vwv01r97

**Comment by goalstogrowth** [comment]
It works better in codesandbox, so it may be a positioning error in the browser. However, I'd still like a combined tooltip to allow for better comparisons.

**Comment by junedchhipa** [comment]
The codesandbox example is a fork of "Basic Vue Chart". Please share your example code on it.

**Comment by junedchhipa** [comment]
Can you please check if the codesandbox demo is updated with your code? I still see the basic example.
