### ISSUE TITLE
How to call another function from an event of Apexcharts?

### ISSUE THREAD

**Issue by SoohyunFantasticJo** [apexcharts/vue-apexcharts#61]
Hello, This SJ.

Can I ask a feature about calling event of Apexcharts?
I want to call a function of Vue instance, if a bar-chart is selected.
But, dataPointSelection event can't call any functions.
How do it can call  another function?
Please help me.

Thank you,
SJ.

--------------------------------------------------------------------------

My source code is as below:

```javascript
data() {
},
methods: {
    functionA : function(index) {
        console.function(index);
    }
}

chart: {
    id: 'vuechart',
    events: {
        dataPointSelection: function(event, chartContext, config) {
            var index = config.selectedDataPoints[0];
            this.functionA(index); // <-- can't call this.functionA()
        }
    }
}
```

**Comment by junedchhipa** [comment]
You have to call Vue methods from an arrow function, as `this` is currently pointing to the chart instance and not the Vue instance.

I have provided a complete example of calling Vue method from inside `dataPointSelection` method in a codepen - https://codepen.io/apexcharts/pen/VgPamb

You will have to move the `chartOptions` to a computed property and convert the function to an ES6 arrow function as shown in the example. In the example, click on the bars and see how it calls the method defined in the Vue instance from ApexCharts event.

The below code is the important part of the script

```js
  computed: {
    chartOptionsYear: function() {
      return {
        chart: {
          events: {
            dataPointSelection: (e, chart, opts) => {
              // you can call Vue methods now as "this" will point to the Vue instance when you use ES6 arrow function
              this.VueDemoMethod();
            },
            updated: function(chart) {
              updateQuarterChart(chart, "barQuarter");
            }
          }
        },
        plotOptions: {
          bar: {
            distributed: true,
          }
        }
      }
    }
  }
```

**Comment by yurirnascimento** [comment]
See #62 pull request.

**Comment by SoohyunFantasticJo** [comment]
Thank you, Junedchhipa & Yurirnascimento.
I solved it thanks to you.
SJ

**Comment by rognales** [comment]
@yurirnascimento can you share some example on merged feature?

this is my current code
```
<apexchart
type="bar"
height="200"
:options="chartOptions"
:series="filteredChartSeries"
v-if="loaded"
@dataPointSelection="clickHandler"
/>
```

methods:{
   clickHandler() {
     
   }
}

How do I access the original props (event, chartContext, config)

**Comment by junedchhipa** [comment]
The original props are in the config param (3rd one) of the function.

**Comment by IgorTitov** [comment]
> You have to call Vue methods from an arrow function, as `this` is currently pointing to the chart instance and not the Vue instance.
> 
> I have provided a complete example of calling Vue method from inside `dataPointSelection` method in a codepen - https://codepen.io/apexcharts/pen/VgPamb
> 
> You will have to move the `chartOptions` to a computed property and convert the function to an ES6 arrow function as shown in the example. In the example, click on the bars and see how it calls the method defined in the Vue instance from ApexCharts event.
> 
> The below code is the important part of the script
> 
> ```js
>   computed: {
>     chartOptionsYear: function() {
>       return {
>         chart: {
>           events: {
>             dataPointSelection: (e, chart, opts) => {
>               // you can call Vue methods now as "this" will point to the Vue instance when you use ES6 arrow function
>               this.VueDemoMethod();
>             },
>             updated: function(chart) {
>               updateQuarterChart(chart, "barQuarter");
>             }
>           }
>         },
>         plotOptions: {
>           bar: {
>             distributed: true,
>           }
>         }
>       }
>     }
>   }
> ```

Hi, could you please hint on how to do it in react-apexchart? Using 'this.DemoMethod();' seems to do nothing regardless of how I define 'DemoMethod' in the React component...
