### ISSUE TITLE
Charts in Tabs not rendering until resize

### ISSUE THREAD

**Issue by muehling** [apexcharts/vue-apexcharts#65]
See example here:

https://codesandbox.io/s/1mzm87884

Two graphs are placed in two tabs (using Bootstrap-Vue). The graphs will not show until the window is resized and when switching between tabs, another resize is needed to get the graphs to show.

I am not sure whether the problem is more related to Bootstrap-Vue or to ApexCharts, but I figured I start here...

**Comment by junedchhipa** [comment]
Can you please update your codesandbox example link? I don't see any tabs in your example.

**Comment by junedchhipa** [comment]
You were using an older version of ApexCharts.
I just updated the versions in this example - https://codesandbox.io/s/188o03vzw4

Please use the latest version - https://cdn.jsdelivr.net/npm/apexcharts@3.5.0
