### ISSUE TITLE
vue-apexcharts dataURI

### ISSUE THREAD

**Issue by avelstorm** [apexcharts/vue-apexcharts#66]
Hi there.

Can you provide us with an example with dataURI.
We are trying to use the dataURI function of vue-apexcharts and we constantly get the error of dataURI is not a function.

we are using vue with webpack (we have updated the libraries to the latest versions).

i am including the file ChartsLineDash3c.txt which is a .vue 

![apex](https://user-images.githubusercontent.com/28759842/53346789-6e133500-3920-11e9-93e7-8bae1bfdc1c0.jpg)

[ChartsLineDash3c.txt](https://github.com/apexcharts/vue-apexcharts/files/2901086/ChartsLineDash3c.txt)

**Comment by caramongr** [comment]
![test1](https://user-images.githubusercontent.com/9036325/53351921-93a53c00-392a-11e9-857e-47d56ae6f4ad.jpg)

Same here

Uncaught TypeError: this.chart.dataURI is not a function

**Comment by junedchhipa** [comment]
The `dataURI()` function from `vue-apexcharts` works fine here - https://codesandbox.io/s/m7m1kp0o1p

ApexCharts version - 3.5.0
Vue-ApexCharts version - 1.2.9
