### ISSUE TITLE
the x axis labels are getting disappeared after refreshing. I am using this.chartOptions.xaxis.categories=x (where x is an array containing x axis labels).

### ISSUE THREAD

**Issue by tanyashr95** [apexcharts/vue-apexcharts#67]
code:

`
async created(){
    
    const url="http://localhost:5000/api/posts/";
    try{
     var NPSdata=await dataService.getData(url+"getNPSdata");
     var x=[];
     var y=[];
     NPSdata.forEach(function(obj)
     {
       x.push(obj.Category);
       y.push(obj.NPS);
     });
      this.chartOptions.xaxis.categories=x;
      this.series[0].data=y;
    }catch(err){
      this.error=err.message;
    }
  }
}
`

i am getting data in console if i print "this.chartOptions.xaxis.categories". If i change the width of graph it shows the labels and then after refreshing it again goes away.

**Comment by junedchhipa** [comment]
Please read the guide on how to update the chart from Vue environment - https://github.com/apexcharts/vue-apexcharts

You should set the outermost prop directly and not just update the nested property.

Like this
```javascript
this.chartOptions = {
  xaxis: {
    categories: x
  }
}

this.series = [{
  data: y
}]
```

Your x should be array of strings (numbers also fine) ['cat1', 'cat2', .... , 'catn']
Your y should be an array of numbers [23, 44, 32, 3, 56, ...., n]

**Comment by tanyashr95** [comment]
thank you ... it worked !! :)
