### ISSUE TITLE
vue-apexchart not getting chart type from option. drawing default line chart

### ISSUE THREAD

**Issue by sanyam53** [apexcharts/vue-apexcharts#68]
<apexcharts  ref="chart2"  :options="chartOptions" :series="series" ></apexcharts>
by not mentioning any chart type in html and defining in options like
chartOptions: {
        chart: {
          id: 'basic-bar', 
          type: 'bar', 
........

it's not working , drawing default line chart not considering this chartoption chart type.
it's working in normal javascript but not in vue.

**Comment by junedchhipa** [comment]
The `type` prop of `<apexcharts>` component will override the `chartOptions.chart.type`.
Hence, it is essential to provide the `type` in the `<apexchart>` component.

**Comment by junedchhipa** [comment]
You should provide `type` like below
```javascript
<template>
   <div>
     <apexchart width="500" type="bar" :options="chartOptions" :series="series"></apexchart>
   </div>
</template>
```

**Comment by sanyam53** [comment]
i want chartOptions.chart.type to override the type prop of <apexcharts>. as i want to set chartOptions.chart.type in method after some event. so you understood reverse of my problem

**Comment by junedchhipa** [comment]
If you change the `type` prop of the component from anywhere, it will update the chart.

**Comment by sanyam53** [comment]
how to set type prop from javascipt?

**Comment by sanyam53** [comment]
document.getElementById("chart").setAttribute('type','line'); this is not working

**Comment by junedchhipa** [comment]
Take a look at this example 

```javascript
<template>
   <div class="app">
     <apexchart width="550" :type="type" :options="chartOptions" :series="series"></apexchart>
     <div>
       <button @click="updateType">Update!</button>
    </div>
   </div>

</template>

export default {
    data: function() {
      return {
        type: 'area'
        chartOptions: {
          chart: {
            id: 'vuechart-example',
          },
          xaxis: {
            categories: [1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998],
          },
        },
        series: [{
          name: 'series-1',
          data: [30, 40, 45, 50, 49, 60, 70, 81]
        }]
      }
    },
    methods: {
      updateType() {
        this.type = 'bar';
      }
    }
};
```

**OR**
If you want to update from another component which is not connected by any relationship, you can try

```javascript
ApexCharts.exec('vuechart-example', 'updateOptions', {
   chart: {
    type: 'bar'
  }
})
```
