### ISSUE TITLE
Pie/Donut chart not working

### ISSUE THREAD

**Issue by LadislavBohm** [apexcharts/vue-apexcharts#69]
Hi,

it seems that pie/donut charts are not working in current release. Using the most basic configuration with just few labels and number in series array.

![image](https://user-images.githubusercontent.com/4920886/54091562-b51e1300-4381-11e9-870f-bb040b04fbe1.png)

[CodePen](https://codepen.io/LadislavBohm/pen/xBLVoq)

**Comment by junedchhipa** [comment]
Thanks for the heads up!
Pushed a big update 2 hours ago, and missed the tests for pie/donuts.
Releasing a patch soon.

**Comment by junedchhipa** [comment]
Released 3.6.1
