### ISSUE TITLE
i want chartOptions.chart.type to override the type prop of < apexcharts >. as i want to set chartOptions.chart.type in method after some event. so you understood reverse of my problem

### ISSUE THREAD

**Issue by sanyam53** [apexcharts/vue-apexcharts#73]
i want chartOptions.chart.type to override the type prop of < apexcharts >. as i want to set chartOptions.chart.type in method after some event. 
_Originally posted by @sanyam53 in https://github.com/apexcharts/vue-apexcharts/issues/68#issuecomment-471405344_

**Comment by junedchhipa** [comment]
Duplicate of #68
