### ISSUE TITLE
chartoptions not updating through updateOptions(chartOptions1,false,true);

### ISSUE THREAD

**Issue by sanyam53** [apexcharts/vue-apexcharts#74]
i am implementing chart drilldown so updating option from chartOptions1 to chartOptions2 not working properly. data(xaxis.categories) gets updated but colors and other chart styling not updating.
same while going backwards from chartOptions2 to chartOptions1 data gets updated but actual chart options not updating.
i am using this.$refs.chart2.updateOptions(this.chartOptions1,false,true);
looks like it's not reactive? do we need to clear chartoption before changing?
can anyone help?

**Comment by sanyam53** [comment]
@junedchhipa can you help with this one?

**Comment by junedchhipa** [comment]
I would appreciate a working codesandbox example for me to look into the issue quickly.
Please use this Vue template to create the example - https://codesandbox.io/s/o7339qql3z

**Comment by junedchhipa** [comment]
Also, this example of a drill-down https://apexcharts.com/vue-chart-demos/column-charts/dynamic-loaded-chart/  might help in case you haven't look at it yet.

**Comment by sanyam53** [comment]
@junedchhipa 
https://codesandbox.io/s/qzl15y1nlj?fontsize=14
i dont know why but click event on bar is not working on sandbox in the above code. it works in my local. can you helm with changing chartoptions?

**Comment by junedchhipa** [comment]
Can you save the codesandbox and share again? It looks like you shared the older version.

**Comment by sanyam53** [comment]
it showing updated in my friend laptop with same link https://codesandbox.io/s/qzl15y1nlj?fontsize=14. i think there is option in toolbar for update available..

**Comment by junedchhipa** [comment]
Ok, I will check again, thanks.

**Comment by sanyam53** [comment]
@junedchhipa are you able to figure it out??

**Comment by junedchhipa** [comment]
@sanyam53 There was a small error on your side while updating the base chart.
You were overwriting the options by
```javascript
this.chartOptions = {
  xaxis: {
    categories: x
  }
};
```
❌ Don't use the above way to update charts

You should update the options like this (as specified in README)
```javascript
this.chartOptions = {...this.chartOptions, ...{
  xaxis: {
      categories: x
  }
}};
```
✅ The above code will preserve the existing options.

I tried doing the same and it works fine now.

Working example on [codesandbox](https://codesandbox.io/s/oq1qzqwq)

**Comment by sanyam53** [comment]
Thanks man

**Comment by SuperService** [comment]
@junedchhipa
I am getting same issues on Vue 3 TypeScript

watch(
() => store.getters.getDashBoard,
(newData) = > {
   profitLineOptions = Object.assign(
   profitLineOptions,
  {
        xaxis: {
             categories: newData
        },
   }
)
}

profitLineOptions value is changed but not updating xaxis categories in UI
I hope you help me
thanks
