### ISSUE TITLE
Is it possible to make Apex-Charts reactive with Vue?

### ISSUE THREAD

**Issue by hAtul89** [apexcharts/vue-apexcharts#87]
This is how my barChart variable under `data() { return { ... } }` looks like, using [Vue-ApexChart][1]  

                barChart:       {

                    chartOptions: {
                        chart:{
                            height: 320,
                            width: "100%",
                            toolbar: {
                                show: false
                            } 
                        },
                        colors: ['#587291', '#1CCAD8', '#00b0f0', '#007bff'],
                        plotOptions: {
                            bar: {
                                horizontal: false,
                                // endingShape: 'rounded',
                                // columnWidth: '55%',
                            },
                        },
                        dataLabels: {
                            enabled: false
                        },
                        stroke: {
                            show: true,
                            width: 2,
                            colors: ['transparent']
                        },

                        xaxis: {
                            // categories: ['col1', 'col2', 'col3', 'col4']
                        },
                        yaxis: {
                            /*title: {
                                text: '$ (thousands)'
                            }*/
                        },
                        fill: {
                            opacity: 1
                        },
                        tooltip: {
                            /*y: {
                                formatter: function (val) {
                                    return "$ " + val + " thousands"
                                }
                            }*/
                        }
                        /*legend: {
                            onItemClick: {
                                toggleDataSeries: true
                            },                            
                        }*/
                    }, 
                    series: [
                        {
                            name: 'option1',
                            data: [44, 55, 57, 56]
                        },
                        {
                            name: 'option2',
                            data: [76, 85, 101, 98]
                        },
                        {
                            name: 'option3',
                            data: [35, 41, 36, 26]
                        },
                        {
                            name: 'option4',
                            data: [35, 41, 36, 26]
                        }
                    ]
                }, 

and this is the HTML part: 

    <chart height="320" type="bar" :options="barChart.chartOptions" :series="barChart.series"></chart>

In one of my methods: 

    this.getList();
    this.barChart.chartOptions.xaxis.categories = Object.keys(this.list);

Is it possible to update the chart "xaxis.categories" part, and get it displayed right away, onchange? 

  [1]: https://apexcharts.com/docs/vue-charts/

**Comment by junedchhipa** [comment]
Yes, that should be the default behavior.
How are you updating the values?

It should be like this
```javascript
this.chartOptions = {...this.chartOptions, ...{
    xaxis: {
        categories: [....]
    }
}}
```

**Comment by hAtul89** [comment]
> Yes, that should be the default behavior.
> How are you updating the values?
> 
> It should be like this
> 
> ```js
> this.chartOptions = {...this.chartOptions, ...{
>     xaxis: {
>         categories: [....]
>     }
> }}
> ```

You mean, this.barChart.chartOptions = { ... }; ? 

And when writing down: 
```
{...this.chartOptions, ...{
>     xaxis: {
>         categories: [....]
>     }
> }}
```

You mean to insert the whole object data? :scream:

**Comment by junedchhipa** [comment]
Yes, you should merge object properties (here with spread syntax) to avoid losing existing config.
No harm in doing that.

**Comment by hAtul89** [comment]
I'm not sure I 100% understand, but you mean, If I want to change the chart xaxis categories, on an already created variable, I just: 

```
                this.barChart = {
                    chartOptions: {
                        xaxis: {
                            categories: Object.keys(this.list)
                        }
                    }
                };
```

Which will change the xaxis categories, and wont touch any other setting (colors/series/ect') except of this one.

**Comment by hAtul89** [comment]
* accidentally closed it :( *

**Comment by junedchhipa** [comment]
Ok! That's the accepted way of updating objects currently.
Closing it for now as there don't seem any issues with `vue-apexcharts` being reactive.
