### ISSUE TITLE
in pie charts the labels are overlapping if the pie angle is less.

### ISSUE THREAD

**Issue by tanyashr95** [apexcharts/vue-apexcharts#89]
https://codepen.io/tanya-shrivastava/pen/zXNxOd

here is the codepen link
<img width="273" alt="Screenshot 2019-04-09 at 3 45 51 PM" src="https://user-images.githubusercontent.com/48240786/55792617-a50f6580-5ade-11e9-9d3c-8e30eea73db5.png">

**Comment by robsontenorio** [comment]
Probably same issue as https://github.com/apexcharts/apexcharts.js/issues/514

**Comment by junedchhipa** [comment]
For pie charts, a new option will be provided to hide labels if they overlap.

```javascript
plotOptions: {
  pie: {
    dataLabels: {
      minAngleToShowLabel: 15
    }
  }
}
```

Using this, you can avoid printing labels for very small slices.

Alternatively, you can also use legend.formatter to display percentages there.
