### ISSUE TITLE
Heatmap enableShades breaks when adding series

### ISSUE THREAD

**Issue by mizujin** [apexcharts/vue-apexcharts#97]
Using : 

vue: 2.6.8,
apexcharts: 2.6.0,
vue-apexcharts : 1.2.7

Dynamically adding series to a graph with the following plotOptions breaks - it causes all series to be colored black. It doesn't occur when only a single series is present. Removing the `enableShades : false` property, or changing it's value to true solves this problem. In my case I don't want shades. 

```javascript
        plotOptions: {
          heatmap: {
            enableShades: false,
            shadeIntensity: 1,
            colorScale: {
              ranges: [{
                  from: 0,
                  to: 2,
                  name: 'From 0 to 2',
                  color: '#D41A0C'
                },
                {
                  from: 2,
                  to: 4,
                  name: 'From 2 to 3',
                  color: '#FACB35'
                },
                {
                  from: 4,
                  to: 5,
                  name: 'From 4 to 5',
                  color: '#009B7C'
                }
              ]
            }
          }
```

<img width="873" alt="Capture d’écran, le 2019-04-30 à 11 30 39" src="https://user-images.githubusercontent.com/7820886/56973745-74e64000-6b3b-11e9-9361-f1f811ce717b.png">
<img width="868" alt="Capture d’écran, le 2019-04-30 à 11 30 49" src="https://user-images.githubusercontent.com/7820886/56973746-74e64000-6b3b-11e9-976d-b9b2b4b59ac4.png">

**Comment by junedchhipa** [comment]
Please upgrade to `apexcharts@3.6.9` and `vue-apexcharts@1.3.4`
